### ISSUE TITLE
As an end-user consuming the Azure SDK for CPP and sending an HTTP request with a Service API, I want to know the checkpoints where the API can be cancelled using the cancelation token.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1064]
Current cancelled checkpoints are:
- BodyStreams which will check and throw before trying to Read().
  - MemoryBodyStream
  - FileBodyStream (Windows and Linux)
  - CurlBodyStream.  Before trying to pull from network.

- RetryPolicy
  - After each `send()` operation that throws a retriable exception (TransportException) and before reaching the MAX retry count.
  - After honoring the `retryAfter` headers (if any).
  - Basically the last thing before re-trying,

- StorageRetryPolicy
  - After each send() operation that is not success.
  - After switching to the secondary Host (if any).
  - Before sleeping (doing the delay before the next try).

- CurlTransportAdapter
  - Before sending (putting) a chunk of data into the socket (network).
  - Each second while waiting for a socket to be ready to read/write with a maximum of 60 seconds (when timeout is then throw). The 60 sec are not the timeout for the entire request to complete. It is the timeout for waiting for the OS to tell us that the socket has some data for us to take or that is ready to be written and send a small chunk to the network. The read/write chunk is 64k for an SSL encoded session.

- WinHttpTransportAdapter

## Conclusion after the below comments:
- Retry policies don't need to check for cancellation.
- For synchronous I/O operations, we can only cancel in between I/Os. So, if we upload 64KB at a time, then we can cancel between each 64KB. Means a transport adapter can keep checking for cancellation in its implementation before each I/O operation.
- Check cancellation on transport policy.
- Update BodyStream base class to provide the cancellation check for Read()
- Remove the cancellation check for all the bodyStream implementations.

The work required for this issue is only then to remove the cancellation check from the retry policies (core and storage)

**Comment by JeffreyRichter** [comment]
At a high level, we want to check cancellation before an I/O request is made and in any long-running loops (which we shouldn't have). The I/O requests are "initiating an HTTP request" and while "sending/reading bytes via a BodyStream".

The retry policies do not need to check this as they are loops but inside the loop is the HTTP request and so the TransportPolicy can check the cancellation before initiating the HTTP request.

If we check in the TransportPolicy, then each HTTP adapter will not have to check so we can remove the check from CurlTransportAdapter. That being said, an adapter should still be passed the context because the implementation MAY decide to enable cancelling of the synchronous I/O operation using a function like this: https://docs.microsoft.com/en-us/windows/win32/fileio/cancelsynchronousio-func

**Comment by vhvb1989** [comment]
@JeffreyRichter, checking the cancellation only in TransportPolicy has a problem;
- If Upload API is called with one single thread to put 10 Gb to Azure Storage, the end-user won't be able to cancel the request once it has started (once we pass the transportPolicy). Say after 1GB has been uploaded. That's why the transportAdapter needs to keep checking for cancellation frequently.

Also, curious question:
In order to use the context object to cancel an I/O operation, as a customer, I have no other option than using a new thread for my request right?. Since C++ is not async, the program would be blocked until the request is terminated unless I use a side thread for that request.
So, why not, as a customer, I can just call terminate on the thread I created to force the cancellation without even using the context?  
We are not currently having any cancellation routine to free or clean anytning. All we use are unique_ptr which will be auto-cleaned. So, terminating the thread would have the same effect, (I think) than calling context.Cancel();.  The only difference is that calling Cancell would throw an exception inside the thread, compared with just killing the thread. 
So, do we really need the context?   Looks like a async-only utility, isn't it?

**Comment by JeffreyRichter** [comment]
The transport could check for cancellation before calling BodyStream's Read or Read's implementation could do it or both could do it.

For customer code to manually/explicitly cancel, yes, another thread would have to do it. If this doesn't happen the THREAD (not program) doing the I/O is blocked until the I/O completes. Terminating a thread is always a bad thing to do for many reasons: 1) the thread's stack leaks until the process terminates. 2) The thread could have acquired resources (like a lock or allocated memory) and these resources will never be unlocked/freed now since the thread isn't returning and therefore won't execute that code that cleans things up. 3) The rest of the program won't know that the thread was killed and won't know what to do next.

The unique_ptr will NOT be cleaned-up because the code to get rid of it (generated by the compiler) won't execute. C++ is not garbage collected. It is better to throw and then the cleanup code execute.

Yes, we need Context as it also expires based on time.

**Comment by vhvb1989** [comment]
> The transport could check for cancellation before calling BodyStream's Read or Read's implementation

Our current implementation reads 64k from the BodyStream up a time (by default) to perform an upload. However, this size can be changed from the HttpRequest to be higher (as high as int64).

There are two possible situations:
- For default behavior, if the network becomes super slow to even upload 64k, the customer won't be able to cancel until it finish.
- For a customer increasing the read side in the request, we would block the cancellation if the adapter is not frequently checking.

About the termination thread, my understanding is that, for C++, we call the destructor thread.std::thread::~thread(); . This works as long as the thread is not join(). Then the thread will call terminate() routine. 
But yest, the time concept would need to be handled by end-user, which is not cool.  
Thanks for the explanation, the time feature makes sense for keeping the context cancellation feature.

**Comment by JeffreyRichter** [comment]
For synchronous I/O operations, we can only cancel in between I/Os. So, if we upload 64KB at a time, then we can cancel between each 64KB. This is OK behavior. If the network is super slow, then cancel will be slow to respond and this is OK. 
The BodyStream's Read is passed the Context so it can look at it and cancel. This does mean that each BodyStream can/should look at the Context - it is passed it after all.

I'd have to look at how std::thread is implemented but in other languages, destructing a thread does NOT kill the thread; it just kills the thread object that is wrapping the thread. The thread dies when it naturally returns. Also, a thread object wrapper can outlive the lifetime of a thread - this is useful to allow join to work or to get the thread's exit code.

**Comment by ahsonkhan** [comment]
That seems reasonable.

> At a high level, we want to check cancellation before an I/O request is made and in any long-running loops (which we shouldn't have). The I/O requests are "initiating an HTTP request" and while "sending/reading bytes via a BodyStream".

Is there any harm or issue with honoring the context cancellation more frequently in an effort to be more responsive, for example before each retry or before any other explicit thread sleeps, say longer than 150 ms?
