### ISSUE TITLE
The retry policy is rewinding the bodystream even though not all streams are rewindable resulting in poor error messages to the user

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1093]
See https://github.com/Azure/azure-sdk-for-cpp/blob/dd65f20a1f9fa6d1405ea5016a7f773da09dce96/sdk/core/azure-core/src/http/retry_policy.cpp#L161-L164

One approach is to do a dynamic cast and do a type check that the stream can be rewound, and only then call it. Otherwise, throw a more meaningful error message and exception.
```text
// pseudocode
1) dynamic cast to check if it is a memory stream, filestream, or other rewindable stream OR call `IsRewindable()`
2) If true, call bodyStream->Rewind();
3) else throw meaningful exception with error message
```

The other approach is to add an `IsRewindable()` method to `BodyStream` similar to `Length()` that let's the caller test the characteristic up front. This is similar to .NET's `Stream.CanSeek` property: https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-5.0

There is a similar issue in reliable stream from storage.
https://github.com/Azure/azure-sdk-for-cpp/blob/dd65f20a1f9fa6d1405ea5016a7f773da09dce96/sdk/storage/azure-storage-common/inc/azure/storage/common/reliable_stream.hpp#L64-L69

cc @vhvb1989, @JeffreyRichter

**Comment by JeffreyRichter** [comment]
The contract is that the upload stream MUST be rewindable as this is the only way to guarantee that retries work. We can throw an exception with a better message; we should NOT add IsRewindable or do any dynamic casting. Passing a non-rewindable stream is a contract violation and the customer MUST fix their code.

**Comment by vhvb1989** [comment]
@JeffreyRichter one of the use cases I remember, of downloading a BodyStream is that, as a user, I can use the bodyStream I got to perform a new operation. For instance, I can call Download and use the return bodyStream to call Upload.
This would be some sort of copying a blob from one place to other without downloading it entirely (but on little peaces).

If we want to support this, We need to make the curl body stream and winhttp body stream to implement the Rewind() method and re-send the original request.  We would currently throw a "Non implemented" exception upon trying to retry when using one of this body streams.

**Comment by ahsonkhan** [comment]
> We can throw an exception with a better message; we should NOT add IsRewindable or do any dynamic casting. 

How are you proposing we detect that the stream is not rewindable to throw the better exception?

**Comment by JeffreyRichter** [comment]
Modify this line of code: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/inc/azure/core/http/body_stream.hpp#L57

**Comment by JeffreyRichter** [comment]
@vhvb1989 Taking a stream from Download and passing it to Upload is not a supported scenario as this cannot be done robustly. That is, we'd be allowing a customer to write code that we can't guarantee will always work. The customer must download entirely to a file/buffer and then can upload from this rewindable stream.

**Comment by vhvb1989** [comment]
@ahsonkhan @JeffreyRichter 
Since this has been around for at least 10 days, would you want to come to a conclusion about what we should do here?

Based on what you commented before, we would only need to improve the text from the exception thrown by the BodyStream to be somethig like 
` Rewind was intented from a body stream which does not support this operation. This could happen if you are trying to use a network body stream (like the response of a Download) to perform a new request and there was an error reading from the Network. The retry policy is then trying to rewind the stream and hence throwing this exception`

Would you agree?

**Comment by ahsonkhan** [comment]
That seems reasonable (and we can wordsmith the exception message itself in a PR). What's the exception type going to be?

Also, I still think we should have a `CanRewind()` bool method on our bodystream type so that the caller can test that before calling `Rewind` rather than relying on catching an exception for control-flow related things. It's the same reason why .NET has both TryParse and Parse methods, one following the tester-doer pattern, and the other throwing an exception since the input might already be pre-validated or assumed correct.

**Comment by JeffreyRichter** [comment]
I would NOT add a CanRewind method - there is no reason to ever call this.
I would change the exception text to this:
The upload BodyStream doesn't support Rewind which is required to guarantee fault tolerance when retrying the operation.

**Comment by ahsonkhan** [comment]
> What's the exception type going to be?

**Comment by ahsonkhan** [comment]
This follows the similar pattern as `Operation<T>`'s `HasValue` and `Value` methods where we expose the "capability" APIs.

**Comment by JeffreyRichter** [comment]
Having HasValue makes sense because it is common for customers to call this first before querying Value. Also, it is common to not have a Value and so the customer has to deal with this.

The only thing that calls Rewind is our upload code - nothing else. And it is our contract that the stream support Rewind. If the stream doesn't support it, then this is a program bug; there is no alternate code path or graceful recovery. The code must be modified. So, I don't expect the exception to be caught - I expect the customer to fix their code.

Also, I don't expect customers to define their own BodyStreams (although they can). When they use ours in Core, then they do already support Rewind (if appropriate). In fact, some client library methods just create our BodyStream and use them correctly; the customer won't even see the BodyStream at all. If the client library code has a bug, we want to find it right away and fix it.

**Comment by ahsonkhan** [comment]
> The only thing that calls Rewind is our upload code - nothing else.

That's only true today. That can and likely will change in the future. I don't think we should be creating public APIs that are strict in not just how they are called, but also exactly where they should be called. If this API is meant to only be called during `Upload`, then why is it public? Any user (including future SDK client libraries) should be allowed to and will call our public APIs in other contexts.

**Comment by JeffreyRichter** [comment]
Why do you think this is likely to change in the future?
I'm happy to make it not be public but what else can we make it?

**Comment by vhvb1989** [comment]
> I'm happy to make it not be public but what else can we make it?

It can be private and the retryPolicy can become a friend class in order to call Rewind().  This would be the option to make it private.

**Comment by JeffreyRichter** [comment]
It is common that a BodyStream-derived object has a field which is also a BodyStream. Calling Rewind on the outer one will likely need to call Rewind on the inner one. So, I think we need Rewind to remain public to allow this.
