### ISSUE TITLE
Should azure core provide a general purpose and reusable pooling API and strategy (even if it is internal only)?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1105]
The curl transport adapter has a connection pooling strategy, using the most recently used cache replacement approach, which was created as a performance optimization
https://github.com/Azure/azure-sdk-for-cpp/blob/6ff9b7b60558717db1c0d012145cb9799aa0d2b1/sdk/core/azure-core/src/http/curl/curl_connection_pool_private.hpp#L38-L83

There isn't a need currently, but one benefit from making this general purpose, is WinHttp could use it as well in the future if required.

Do we foresee **other** areas within Azure::Core benefitting from and re-using it outside of the transport layer and HTTP stacks?

cc @RickWinter, @vhvb1989, @JeffreyRichter

**Comment by JeffreyRichter** [comment]
I do not foresee other areas needing the connection pool code.

**Comment by vhvb1989** [comment]
@JeffreyRichter  The way our SDK client is designed ends up hiding the actual HTTP stack that is used behind a transport adapter.

If we use curl, end customers picks the curlTransportAdapter, but there is no access to a libcurl handle.
If we use winhttp, end customer picks the winHttpTransportAdapter, but there is no direct access to a winHttp handler.
For a custom adapter, the end customer could expose the http stack if they want. End user can creat a new libcurl transport adapter and grant direct access to a libcurl handle.

I mentioned the above context because an HTTP stacks usually creates a handle for sending a request, and in order to re-use the same connection, that same handle is used for a new request.

We created the curl connection pool so we can re-use handles that we create before.

The same thing will be required for any transport adapter that won't expose the connection handle for the end-user. The transport adapter can only create a new handle and clean it per request.  Unless there is something like the pool to move it and reuse it latter instead of creating a new connection handle.

Now, each transportAdapter could implement its own pool, or we can abstract it directly in the transport policy per client. Then, the transportAdapter will ask the transportPolocy for a connection instead of from a particular pool. The transport policy would return the right implementation for that connection.

I can set up a call to explain it better

**Comment by vhvb1989** [comment]
I am closing this issue as something we don't need to implement for any other transport than libcurl.
