### ISSUE TITLE
Add something like `HttpRange` in .Net

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1136]
```c  
Azure::Storage::Blobs::PageRange
```
#
We added an `HttpRange` type in `::Core` for this.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/HttpRange.cs

**Comment by Jinming-Hu** [comment]
Actually it's nothing but

```C++
struct HttpRange {
    int64_t Offset;
    int64_t Length;
};
```

**Comment by Jinming-Hu** [comment]
Can we reconsider the name `HttpRange`? Because I think HTTP is a protocol, it's not something we can apply a range to. How about `ContentRange`, `BlobRange`, `FileRange` or just `Range`?

**Comment by vhvb1989** [comment]
Assigning to @JeffreyRichter to review and decide if we want to have this on Core or if it should be Storage only.
The question is, is any other service using the range header as part of the requests?

**Comment by JeffreyRichter** [comment]
Yes, I'm happy to add this to Core.

**Comment by Jinming-Hu** [comment]
> What if we just call it Range and put it in the HTTP namespace.

`Range` is great!

**Comment by ahsonkhan** [comment]
Range is too short and common which leads to it being easily overloaded. For example, C++ 20 STL already has Ranges:
https://en.cppreference.com/w/cpp/ranges
https://en.cppreference.com/w/cpp/ranges/range

We should prefix it with something like `HttpRange` so that it isn't too generic. I would imagine that's why .NET went with that name as well (to avoid clashing with [Range](https://docs.microsoft.com/en-us/dotnet/api/system.range?view=net-5.0) type.

**Comment by vhvb1989** [comment]
> Range is too short and common which leads to it being easily overloaded

It is within HTTP namespace

**Comment by Jinming-Hu** [comment]
> Range is too short and common which leads to it being easily overloaded. For example, C++ 20 STL already has Ranges:
> https://en.cppreference.com/w/cpp/ranges
> https://en.cppreference.com/w/cpp/ranges/range
> 
> We should prefix it with something like `HttpRange` so that it isn't too generic. I would imagine that's why .NET went with that name as well (to avoid clashing with [Range](https://docs.microsoft.com/en-us/dotnet/api/system.range?view=net-5.0) type.

I understand you worry about name clash. But they're in different namespaces. This is what namespace in C++ was invented for, right?

**Comment by ahsonkhan** [comment]
In code snippets/samples, most folks will have a `using namespace Azure::Core::Http;` and then use it as:
```C++
Range r{10, 1};
```
That is quite generic for such a functionally specific type.

> But they're in different namespaces. This is what namespace in C++ was invented for, right?

The same could be said about .NET's `HttpRange` type, it isn't in the `System` namespace but rather in `Azure`, so why wouldn't they keep it as `Range`?

@tg-msft What do you think of using `Range` as the type name here? Why wasn't `HttpRange` added to the Http namespace in .NET and if it was, would you have dropped the `Http` prefix?

**Comment by tg-msft** [comment]
We picked `HttpRange` because it corresponds exactly to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range (although some of the values like `units` are assumed to be `bytes` today, etc., and we won't add support for anything else until we have a scenario that requires it).  We'd also never be able to use just `Range` because of `System.Range` and the new C# syntax for it.

There's a chance we'll regret not having a distinct `Http` namespace if another protocol meaningfully challenges HTTP in terms of adoption among Azure services, but we didn't optimize for that hypothetical when it came to the usability of our core primitives.
