### ISSUE TITLE
Clients should NOT return Response<void>.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1343]
Need to add some test cases to verify clients always return a valid model type.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/issues/1331#issuecomment-759145568_

**Comment by Jinming-Hu** [comment]
Do we have tests cases for `Response<T>` already? If not, we might also need to add tests for it.

**Comment by antkmsft** [comment]
Holding off for now, since we may end up reconsidering `Response<void>`.

**Comment by ahsonkhan** [comment]
Here's an example usage in public API that would need to change:
https://github.com/Azure/azure-sdk-for-cpp/blob/90430040d5b446ade88caf2400f344040be16cb3/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_service_client.hpp#L199-L201

**Comment by vhvb1989** [comment]
@RickWinter since this issue became a feature request, I now wonder..  If we can't return Response<void>, then how can I, as an end-user, take a look to the raw response?  The raw http response is always in the Response<T>, even when T is void

**Comment by Jinming-Hu** [comment]
Why do we need to change `Response<void>`? and what's the alternative?

**Comment by Jinming-Hu** [comment]
You gotta tell me what to be before I can take some action. I think `Response<void>` is just fine.

**Comment by vhvb1989** [comment]
@RickWinter  this came from Ted's feedback right?  Can you address Jinming's inquiry please

**Comment by Jinming-Hu** [comment]
For all storage API, i've been following a consistent pattern:

1. If the API operates the same resource as the client is referencing, like `BlobClient::Create`, `BlobContainerClient::GetMetadata`, it returns a `Response<XxxResult>`
2. If the API operates a child resource, like `BlobContainerClient::UploadBlob`, it returns a response of child client, like `BlobContainerClient::UploadBlob` returns `Response<BlockBlobClient>`.
3. An exception of Case 2), if the API deletes a child resource, like `BlobContainerClient::DeleteBlob`, it doesn't return a response of child client, since the resource will be deleted, child resource client won't be of any use.

I understand that you might have some concern about case 3), but I'm just trying to align with .Net. I cannot come up with any better idea. I'm open to suggestions.

**Comment by Jinming-Hu** [comment]
Not actionable item, don't know what i'm suppose to do here. assign back to core sdk team.

**Comment by RickWinter** [comment]
We do not want to return Response<void>.  Its a pattern that is hard for users to understand.  Instead every API should return a Model that encapsulates the "Response".  In the case of DeleteBlob we should return a type that user can use to know the blob was deleted.

**Comment by Jinming-Hu** [comment]
> We do not want to return Response. Its a pattern that is hard for users to understand. Instead every API should return a Model that encapsulates the "Response". In the case of DeleteBlob we should return a type that user can use to know the blob was deleted.

So do you suggest `Response<bool>` or `Response<DeleteBlobResult>`?

**Comment by Jinming-Hu** [comment]
I'll go with `Response<DeleteBlobResult>` if nobody has preference or suggestion.
