### ISSUE TITLE
Pipeline caching step intermittentily fails with "No such host is known" during `GenerateReleaseArtifacts` CI step

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1361]
There is an intermittent vcpkg cache issue during `GenerateReleaseArtifacts` step:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=686439&view=logs&j=a129effc-2dd1-54d1-fb5a-ad7bdc0e851d&t=b1cedf96-772d-5777-7b77-39b3ac0fcc40

@danieljurek can we add some sort of retry here or reduce the brittleness in some way to increase build reliability, unless we are accidentally hitting some Azure KeyVault limit:
https://github.com/Azure/azure-sdk-for-net/issues/7873#issuecomment-537338521 (cc @mitchdenny )
```text
Resolved to: GenerateReleaseArtifacts|"tags/2020.11"|Windows_NT|curl[winssl] libxml2 nlohmann-json

##[error]No such host is known.
```

For context, we are currently applying this approach to get vcpkg caching to reduce build times which requires us to restore them via the keys:
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

**Comment by danieljurek** [comment]
We could add `continueOnError: true` to the cache job. If it fails we re-run the whole vcpkg process. 

Both situations (downloading the file cache or cloning vcpkg and downloading package source artifacts to build) require network connections so if the machine encounters a network issue like the kind that would cause the failure in the vcpkg cache step we may hit the same network issue later on. I don't see this clearly improving reliability but it also shouldn't hurt things.

**Comment by danieljurek** [comment]
Chatted with someone who has more experience with the Cache task. Adding `continueOnError: true` could introduce other strange failures and won't necessarily improve the reliability in the case of intermittent network failures. 

If the cache step fails because of a network issue and we decide to move forward in the build with `continueOnError: true` then the failure modes look like: 

* Before downloading and decompressing files from the cache: no problem, we can continue
* In the middle of downloading and unpacking: the vcpkg tree will be in a partial state. We might have the files we need, we might not. When we move forward and clone the directory won't be empty and the build will fail. In this case the errors you get may be more removed from the primary contributing factor (network issue) 

To that end I recommend that we keep things as they are. Retry jobs that fail on intermittent network issues and those jobs will generally get past the failed cache step. 

cc @mitchdenny

**Comment by ahsonkhan** [comment]
> Retry jobs that fail on intermittent network issues and those jobs will generally get past the failed cache step.

Can we add a systematic auto-retry (maybe 2-3x) in devops, and report the intermittent failures like these as "warnings", so that we don't have to manually trigger a retry? Or would that end up hiding some real intermittent bugs/test failures in the SDK that need to be investigated?

**Comment by ahsonkhan** [comment]
Another intermittent failure due to a different reason, from https://github.com/Azure/azure-sdk-for-cpp/pull/1741: `##[error]The operation was canceled.`

https://dev.azure.com/azure-sdk/public/_build/results?buildId=754078&view=logs&j=f578152f-9f12-52ef-8faa-e76d6b953f78&t=d3aa4999-29fb-5ed2-a561-16a602d718a5

**Comment by danieljurek** [comment]
26 minutes is a long time to wait for a response before failing. I can set a timeout on this step to save agent time and dev headache. Need to investigate whether we have data for average run time of a successful cache unpacking.

**Comment by danieljurek** [comment]
After some discussion and analysis of a subset of `Vcpkg Cache` runs we are going to start with a timeout at 10 minutes. The overall average run time of successful (cache hit or cache miss) `Vcpkg Cache` runs is under 1 minute.
