### ISSUE TITLE
Investigate and fix building and linking azure-identity and azure-core on arm64-windows.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1367]
Figure out and fix the linker issue between azure-identity and `DateTime`, specifically the private static `SystemClockEpoch` on arm64-windows.

See for more context:
https://github.com/azure-sdk/vcpkg/pull/3
https://github.com/microsoft/vcpkg/pull/15635

We probably also want to investigate how we can add this configuration in our CI, but that is a separate issue: https://github.com/Azure/azure-sdk-for-cpp/issues/1368

cc @antkmsft

**Comment by antkmsft** [comment]
UWP is also affected. it can be worked around, but the next thing that will fail in the same manner will be all the extensible enums from Storage, specifically ones that are actually getting used in our code (customers would run into the same problem if the would try to consume them).

I think that it might be a problem with cmake - we do use `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`, which works as expected for desktop builds, but apparently not for UWP or ARM.

Since we cannot retroactively fix cmake, I think our only solution would be to use `declspec(dllimport/dllexport)` for static variables. (apparently, functions are fine, i.e. `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` does some part, but not all)

**Comment by ahsonkhan** [comment]
@antkmsft I don't think much has changed in the last week for other errors to bubble up. We had VCPKG CI passing in your draft PR 8 days ago, here: https://github.com/microsoft/vcpkg/pull/15471

**Comment by antkmsft** [comment]
DaetTime did not have static data member back then. And with extensible enum - you won't see linker error until you try to consume them - either when customer tries to, or when one of our SDK client libraries tries to consume an extensible enum from another client library. I saw the extensible enum change for storage, going in on Jan 5th, not so long ago, plus I assume maybe it was not consumed immediately. So, it is possible it was just the right timing for the initial PR validation to be submitted without that change.
