### ISSUE TITLE
Can public types inherit from "private" base classes (under the "Details"/"Internal" namespaces) - DateTime?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1599]
@CaseyCarter can you please share your thoughts on this question.

See the following:
https://github.com/Azure/azure-sdk-for-cpp/blob/87cce3910fefd24a63d0f366b9b9e1f97d326d37/sdk/core/azure-core/inc/azure/core/datetime.hpp#L52

Here's the contract we provide to the customers to help answer this question:
1) **public** - The API is stable and publicly accessible from any caller (both outside the package, and outside the repo). We guarantee this won't have any breaking changes such as renames, moves, removal, etc. Outside of the `public` access modifier keyword, this is indicated by the APIs being accessible from public headers within the `inc/` folder.
2) **internal** - The API should not be called by anyone outside of the repo and not meant for end-users. It is only meant as a mechanism to share code with other packages and service author within the repo. Breaking changes are allowed and all callers would be updated when such a change occurs. This intention is indicated by putting such types in the `Internal::` sub-namespace, and/or an `_internal` suffix to the header name.
3) **private** - This is an implementation detail within a package. It is not meant for anyone outside of the package to call, even if they are within the repo. The author reserves the right to make any breaking changes and it's the responsibility of the caller to react, if they choose to take a dependency, which we don't recommend. Outside of the `private` access modifier keyword from C++, this intention is indicated by putting such types in the `Details::` sub-namespace, moving such headers into the `src/` directory rather than `inc/`, and/or adding a `_private` suffix to the header name.

@RickWinter, we'd want a guideline update for this.

cc @antkmsft, @JeffreyRichter

**Comment by Jinming-Hu** [comment]
I feel you guys are so pedantic about what should be Internal/Details😄😄😄

**Comment by ahsonkhan** [comment]
We don't want to break customers post-GA :)

**Comment by JeffreyRichter** [comment]
@Jinming-Hu : When I was on the CLR team nay years ago, we learned that adding a new feature was 1% effort and that the other 99% of the effort is documenting, testing, supporting, and versioning whatever we implemented. In addition, having a large API surface area is overwhelming to customers and adds confusion (for example, .NET has several XML & JSON (de)serializers and customers don't know which one to use in which circumstances).

So, we DO take this very seriously because this is how we make a usable, sustainable SDK that lives over many years/versions. Also, the less we expose, the less work we have to do (docs, testing, support, etc.) - this improves our sustainability.

**Comment by vhvb1989** [comment]
I would answer to this question with "Yes, they can"

My rationale about it is:  By using ::Details, we want to avoid anyone but the package to directly use what's inside of it.
However, I would expect that if we want to expose the functionality-only of private things (something like a read-only access, non-creation) through public components, to be possible with `well known conditions`.

The well known condition -> Add an exception to our rule about "breaking changes allowed" to private and internal components to say "if the functionality of the component is exposed through a public component, then we can no longer do breaking changes to it". The private/internal component becomes an special type which is non-breakable but non expected for direct usage.

In the example of this issue, we would never make a breaking change to  `::Details::Clock::time_point` (which we probably don't want anyway).  But we are making sure that the only way to use this component's functionality is by creating a `DateTime`.  End-users are advised about not using ::Details.

One may ask, "why not then just making `Details::Clock::time_point` public"??
And my answer is that we want to discourage people from using it directly. We want this way as a way to say `use Datetime instead to get the user-experience we want you to have`.  If we just make it public, there's nothing asking people not to try using the type directly, and nothing letting us to relax the documentation and support for that type.

**Comment by vhvb1989** [comment]
ping @CaseyCarter

**Comment by CaseyCarter** [comment]
I think the confusion here is a consequence of our policy of allowing/forbidding users to access SDK components based on names. The problem is that a user can do virtually anything they like with `Details::Clock` without using that name because the type that it names is publicly exposed. We _have_ documented that `Azure::Core::DateTime` publicly inherits from a specialization of `std::time_point`, so it's trivial to use the name `Azure::Core::DateTime::clock` that denotes the same type as `Azure::Core::Details::Clock` with ever typing `Details`.

By using a `Details` name for this type we're giving non-expert maintainers a false sense of security about making potentially-breaking changes. We've given users the keys to the kingdom by exposing this type in the public interface, so we may as well define it in the public namespace to make that fact equally clear to everyone.

**Comment by ahsonkhan** [comment]
> We've given users the keys to the kingdom by exposing this type in the public interface, so we may as well define it in the public namespace to make that fact equally clear to everyone.

+1 - I agree, though unfortunate, that is the most honest reflection of what's currently happening.
I think we had previously discussed that there is still a _slight_ benefit of keeping it in details, enough to avoid having it be "public", because we might be able to rename the `Clock` type, and the user wouldn't be impacted unless they explicitly wrote `Details`. Arguably, that's good enough of a reason to keep it "hidden". Thoughts?

@CaseyCarter can you think of a workaround that removes those keys, i.e. create a mechanism so the customer cannot rely on this type unless they explicitly wrote `Details`?

**Comment by antkmsft** [comment]
Other benefit is that "Clock" type is not cluttering the Azure namespace.
Should you have derived from an other `std::` class not requiring a class in `_detail` namespace, it would also have inherited members such as `::clock`.

I see no problem if customer is using `DateTime::clock` type, because `DateTime` is `std::chrono::time_point<T>`, and `time_point` has `::clock` member. If customers have to write `Azure::_detail::Clock` - they are going where they should not go. If they use `DateTime::clock` - they are are within the allowed boundaries.

Should we disallow this, I think the Clock class must become a nested class inside `DateTime`, `DateTime` should stop inheriting time_point, and we should write implicit conversion operators into `DateTime::time_point<DateTime::Clock>` + all the operators to ensure that DateTime can still be semantically used everywhere where `std::chrono::time_point` can.

Other thing impacted would be `_internal::ClientOptions`.

**Comment by CaseyCarter** [comment]
> @CaseyCarter can you think of a workaround that removes those keys, i.e. create a mechanism so the customer cannot rely on this type unless they explicitly wrote `Details`?

To do that we'd have to remove the type from the public interface, which would break the (IIUC) intentional design feature that `DateTime`s implicitly convert to `DateTime::time_point`.

> I see no problem if customer is using `DateTime::clock` type, because `DateTime` is `std::chrono::time_point<T>`, and `time_point` has `::clock` member. If customers have to write `Azure::_detail::Clock` - they are going where they should not go. If they use `DateTime::clock` - they are are within the allowed boundaries.

I interpret this as "we're perfectly happy that users have access to this type; the only reason we put it in `Details` is to avoid having the name appear in IDE autocomplete". Let me know if that's incorrect.

> Should we disallow this, I think the Clock class must become a nested class inside `DateTime`, `DateTime` should stop inheriting time_point, and we should write implicit conversion operators into `DateTime::time_point<DateTime::Clock>` + all the operators to ensure that DateTime can still be semantically used everywhere where `std::chrono::time_point` can.

Using a nested type looks like a great solution for the naming issue until you run into the "we have to reimplement all the operators the standard library defines" problem which is both a current timesink and a maintenance task ensuring the set of operators stays synchronized if the standard library changes.

Maybe the solution here is to add another special nested namespace for public components whose names shouldn't appear in autocomplete, not because users shouldn't use them but because we want to steer users toward other components they should prefer?

**Comment by ahsonkhan** [comment]
This has been a fruitful and interesting conversation for us to better understand the semantics and edge cases of public, internal, and detail. Given we have already (intentionally) GA'd with the current design, and we are OK to make an explicit exception for a type like DateTime so that it can inherit from a "private" type, which we'll be cognizant to avoid breaking.

I recommend we add a comment to the Clock type in source, to let maintainers know not to make breaking changes to this type since it is indirectly exposed via inheritance to get the chrono::time_point usability we want for the customer.

Unless folks have other thoughts, this issue largely becomes about updating the guidelines about the public/internal/detail semantics (which we may want to track separately) or just closing.

**Comment by RickWinter** [comment]
This is a guidelines update work item
