### ISSUE TITLE
Why does modified-time access condition derive from etag access condition?

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1608]
Hi Rick, I'm looking at your PR this https://github.com/Azure/azure-sdk-for-cpp/pull/1592 and working on using this access condition in storage sdk.

I cannot understand why inheritance should be used here. I was under the impression that, inheritance is always something like dog is an animal so animal is base class and dog is derived class. How is request access condition like that?

This inheritance relationship doesn't work for some storage API. Search `Set Container Metadata` in this page
https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations, this API only supports `If-Modified-Since` access condition. Also `Delete Container` doesn't support etag access condition

**Comment by RickWinter** [comment]
@Jinming-Hu MatchConditions and RequestConditions are general purpose conditional request modifiers for all services.  It unfortunate that storage api's are inconsistent and all do not accept the all conditional request modifiers.

I would follow what the other 4 languages do.  I notice that the .NET SDK will accept all 4 even though as you pointed out all 4 are not accepted by the service.  They then throw if the IfMatch or IfNoneMatch are specified.
```
if (conditions?.IfMatch != default ||
                        conditions?.IfNoneMatch != default)
                    {
                        throw BlobErrors.BlobConditionsMustBeDefault(nameof(RequestConditions.IfMatch), nameof(RequestConditions.IfNoneMatch));
                    }
```

**Comment by Jinming-Hu** [comment]
I don't know what I'm supposed to do here. This looks like pre-condition and according to C++ guidelines, we should crash rather than throw exceptions. Still I do not understand why inheritance has to be used.

@JeffreyRichter @tg-msft Can you please help out here?

**Comment by JeffreyRichter** [comment]
@Jinming-Hu is really correct. For C++, let's keep our MatchConditions structure as-is and NOT derive our RequestConditions from MatchConditions - derive it from nothing. Also, let's rename RequestConditions to ModifiedConditions.

**Comment by Jinming-Hu** [comment]
@RickWinter I assigned this issue back to you.

**Comment by ahsonkhan** [comment]
Ignoring GoLang (since it doesn't have inheritance), this change means we'll be different from all the other "OOP" friendly languages who decided to keep the inheritance structure. What's the drawback of their approach and is it worth it to be different here?

https://github.com/Azure/azure-sdk-for-java/blob/385a9f53e542689571cb407696b6f458d957196f/sdk/core/azure-core/src/main/java/com/azure/core/http/RequestConditions.java#L14-L16
https://github.com/Azure/azure-sdk-for-net/blob/a318e4154d56728fc6a22f8b4ce1c1d0c36a7d7c/sdk/core/Azure.Core/src/RequestConditions.cs#L11-L12

**Comment by Jinming-Hu** [comment]
Other language sdk doing so doesn't justify the correctness. They sometimes make mistakes. Most of the times it's good to take reference from them, but not always.

> What's the drawback of their approach and is it worth it to be different here?

If `RequestConditions` inherits from `MatchConditions`, it implies that any REST API supports if-modified-since/if-unmodified-since has to also support etag match/non-match . This is simply not true. It's not stated anywhere in any documentation. We do have API that only supports if-modified-since/if-unmodified-since while does not support etag.

**Comment by JeffreyRichter** [comment]
Technically, Jinming is correct. From a raw HTTP perspective, MatchConditions and ModifiedConditions are different and many services support MatchConditions while few services support ModifiedConditions. So, from an HTTP perspective, there is no relationship between match & modified conditions and therefore these 2 types should not be related to each other. One could even go so far as to say that many services support If-Math and not If-None-Match so even the match conditions structure could not exist and just the one or two fields could be explicitly specified for the operations that support one or both fields. However, it adds context to customers to wrap these two fields in a thing called MatchConditions and a thing called ModifiedConditions. 

The other languages are really mistaken to draw the relationship that Modified (or Request) Conditions is derived from MatchConditions and I think I'm responsible for some of this. When I was on the Storage team, all I cared about was Storage and I think all (or almost all) operations take Match AND Modified conditions, so I merged them together into 1 structure: https://github.com/Azure/azure-storage-blob-go/blob/master/azblob/access_conditions.go#L8

Then, as other languages and services got on board, the separation occurred because many services don't support Modified conditions but the separation was incomplete and the derivation remained. So, we have a chance to do the better thing in C++ and I think we should take advantage of that.
