### ISSUE TITLE
The `Metadata` type from Storage is exposing a type that is meant to be private in public surface area via type alias

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1626]
Public APIs that accept `Metadata` are leaking a type from the `Details::` namespace, specifically `CaseInsensitiveComparator` because of the type alias. Given `Metadata` is an alias for a custom templated map, the user ends up relying on a private implementation detail, which goes against the guidelines, which means we wouldn't be able to rename or otherwise break the type.
https://github.com/Azure/azure-sdk-for-cpp/blob/76db013528d60e3f54919628747dd990a9c36600/sdk/storage/azure-storage-common/inc/azure/storage/common/storage_common.hpp#L69

For example, see:
https://github.com/Azure/azure-sdk-for-cpp/blob/90430040d5b446ade88caf2400f344040be16cb3/sdk/storage/azure-storage-files-shares/inc/azure/storage/files/shares/share_directory_client.hpp#L163-L165
https://github.com/Azure/azure-sdk-for-cpp/blob/90430040d5b446ade88caf2400f344040be16cb3/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_file_system_client.hpp#L143-L146
https://github.com/Azure/azure-sdk-for-cpp/blob/90430040d5b446ade88caf2400f344040be16cb3/sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_options.hpp#L110-L128

cc @Jinming-Hu, @JeffreyRichter

**Comment by JeffreyRichter** [comment]
My recommendation here is for Storage to create a Metadata class that has a private field of this type: std::map<std::string, std::string, Details::CaseInsensitiveComparator>. 
Then, replicate the map's methods on this Metadata type (or whichever methods make sense for Metadata - maybe not all methods make sense). You could hard code strings for the keys/values. since metadata must always be string/string pairs.

**Comment by Jinming-Hu** [comment]
> My recommendation here is for Storage to create a Metadata class that has a private field of this type: std::map<std::string, std::string, Details::CaseInsensitiveComparator>.
Then, replicate the map's methods on this Metadata type (or whichever methods make sense for Metadata - maybe not all methods make sense). You could hard code strings for the keys/values. since metadata must always be string/string pairs.

I believe your recommendation works, but that sounds to me like an overkill.

What's the worst thing that could happen if we just keep things as is?

**Comment by Jinming-Hu** [comment]
Anyway, I know core sdk team is working on a case-insensitive map, so I'm gonna switch to that some time in the future.

**Comment by JeffreyRichter** [comment]
Yes, I guess we could have one and we could use it for headers as well as metadata. And, maybe even query parameters.
