### ISSUE TITLE
Find a mechanism to hide the JSON dependency (which is an implementation detail) by wrapping it in public API

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1671]
The goal of taking an external JSON dependency had always been: This is an implementation detail, that we can swap out and change any time in the future, and have no impact to the end customer of the SDK. Essentially, changing the JSON library underneath shouldn't be a breaking change.

Expose something like a `JsonSerializer` public API which is made available in core that other services like storage can take a dependency on.

This is similar to `JsonObjectSerializer` in .NET:
https://github.com/Azure/azure-sdk-for-net/blob/12248552a1737eafdd2513c109b19c7cb3497b36/sdk/core/Azure.Core/src/Serialization/JsonObjectSerializer.cs#L18

This design is motivated by the fact that C++ doesn't have a great "internal" approach, and the SDK ships as source rather than a compiled binary. Because each service package ships at independent cadence and timeline, using the `::Internals` namespace doesn't help guard against making such breaking changes, even if the end-customer doesn't call any of the APIs in that namespace directly.

cc @RickWinter, @JeffreyRichter

**Comment by vhvb1989** [comment]
What if we just decide to keep the implementation we have as the one we will keep forever?
The current Json API under ::Internal would be considered backward compatibility for any service and we commit to never change the interface.

If we ever want to change the implementation, we would do it, but keeping the same interface we currently have and working underneath it.

The benefit of this is to avoid creating our own json interface abstraction and then the adapter (or mapping) to our current implementation.  Because even in the future, replacing the implementation would mean creating a new adapter to our abstraction.

So, I would say, let's call the current interface as our interface.  Let's not shoot ourselves in the foot by bringing an extra layer of abstraction.

**Comment by ahsonkhan** [comment]
> would be considered backward compatibility for any service and we commit to never change the interface

We cannot take a dependency on a third party library not making breaking changes, especially when we need to take security or other critical fixes.

> The benefit of this is to avoid creating our own json interface abstraction and then the adapter (or mapping) to our current implementation.

What's the benefit here, exactly?

> let's call the current interface as our interface

That library also provides a large API surface, well beyond what we actually need, so that puts undue burden on the SDK to maintain all of them.

We would have to take the entire interface through API review.

**Comment by vhvb1989** [comment]
> We cannot take a dependency on a third party library not making breaking changes, especially when we need to take security or other critical fixes.

I am not saying we take a dependency on 3rd party. I am saying, we consider the 3rd party interface we already have embedded in our Internal layer to be non-breakable.  If we ever want to migrate to a newer version of the current library we have, we would learn about the changes and fin the way to apply them without breaking.  I basically say, let's maintain the our fork.

> What's the benefit here, exactly?

Not creating the wrapping public API.  It's a valueless peace of code because there is no benefit for end customer, only more work for us now and for the future.

> We would have to take the entire interface through API review.

We are not taking Internal components to APIReview.

**Comment by JeffreyRichter** [comment]
How can we do this if C++ doesn't have any kind of metadata/reflection facility?

**Comment by ahsonkhan** [comment]
Not having reflection capabilities in C++ or attributes to carry metadata certainly makes it difficult.

It may be possible to get around it though. For example, we could have cpp source only dependency on the JSON library (rather than expose via headers) and have each type own the Serialize/Deserialize method. And we can provide implement an "ISerializable"-like interface on the Azure Core types to help customers who incorporate them in their model types.

We have something like this already for keyvault and the `KeyRequestParameters`:
https://github.com/Azure/azure-sdk-for-cpp/blob/1f849ec38435c3151fa358b5cf2073857a83e04d/sdk/core/azure-core/inc/azure/core/internal/json_serializable.hpp#L27
https://github.com/Azure/azure-sdk-for-cpp/blob/3b9a465a4f24859be2c7a9e921e9384013082002/sdk/keyvault/azure-security-keyvault-keys/src/key_request_parameters.cpp#L13-L16

Other alternatives is to design an interface which requires the caller to provide all the `Metadata` (such as property names) and type information up front, possibly using a "sidecar" metadata file. That could be difficult from a usability perspective, if hand-crafted, but we might be able to auto-gen that and emit the sources for it at compile time.

**Comment by bhardwajs** [comment]
@ahsonkhan - How would a client of the SDK consume SDK? Is the current plan to only support CMake as the build system?

One approach would be to use templates till C++20 and concepts starting in C++ 20 to support the `Serialize()` behavior you are showing above. It would be preferable to not have the cost of a virtual function.

Since `json` is an implementation detail, SDK shouldn't expose `nlohmann::json` in build and/or install dependency for a customer and therefore, `json.hpp` shouldn't be in a header file.

**Comment by vhvb1989** [comment]
@bhardwajs about:

>json.hpp shouldn't be in a header file.

Azure Core provides an `interal` API layer that is used by the Azure Service clients like Storage, KeyVault, etc.  We don't want each service to bring it's own json impl or duplicate.  Azure Core exposes a copy of nlohmann API wrapped under an Azure::Core::_interal::Json namespace.

Customers don't need to install nlohmann lib, the SDK contains a copy to not depend on it.
And customers can use any version of nlohmann lib together with the Azure SDK without crashing or issues (thanks to the namespace wrapping).

@ahsonkhan  can we close this issue now? I think we are currently in a good strategy-state

**Comment by vhvb1989** [comment]
@ahsonkhan , if not closing, can we move this backlog?  We have been pushing this issue since Feb milestone to the actual (May). If we ever agree to create the json-replace-abstractio similar to the transport-adapter, it can be after GA right?

**Comment by vhvb1989** [comment]
Decided to close for now. 
Feel free to re-open to re-prioritize this one
