### ISSUE TITLE
Unify Azure::Core::Internal::Http and Azure::Core::Http::Internal

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1702]
https://github.com/Azure/azure-sdk-for-cpp/blob/5c2d0fba17248db31751b202557a2b50554c5726/sdk/core/azure-core/inc/azure/core/http/policy.hpp#L385

https://github.com/Azure/azure-sdk-for-cpp/blob/5c2d0fba17248db31751b202557a2b50554c5726/sdk/core/azure-core/inc/azure/core/internal/http/pipeline.hpp#L19

what should go into one and what should go into the other?

**Comment by RickWinter** [comment]
They will be one.  We are cleaning up the Azure namespaces
Commonly used types for customers reside in `Azure::`
More advanced features for customers which ship in core are in subnamespaces `Azure::<subnamespace>`, i.e. `Azure::Cryptography::`

Features intended for use by client libraries are in or under  `Azure::Core::Internal`
Things private to the `Azure::Core` package are in `Azure::Core::Details`

**Comment by ahsonkhan** [comment]
> Features intended for use by client libraries are in or under  `Azure::Core::Internal`

To clarify this particular aspect, are you recommending we don't have any other `Azure::<subnamespace>::Internal` namespaces, and all such "internal-only" APIs will live under **one** namespace with Internal, i.e. `Azure::Core::Internal`?

For example, what happens when we have some advance feature in `Azure::Cryptography::`, and then we have "internal-only" APIs that are specific to that namespace and would be grouped under `Azure::Cryptography::Internal`? Would those still live under `Azure::Core::Internal`?

**Comment by vhvb1989** [comment]
>  are you recommending we don't have any other Azure::<subnamespace>::Internal namespaces,

I would stay with the `Azure::<subnamespace>::Internal`, The intention is that if you include one header like http.hpp, you would get both public and internal namespaces and you can access it through `Azure::Core::Http`

**Comment by RickWinter** [comment]
As part of the cleanup we will address this
