### ISSUE TITLE
Error response should not have the response body written to customer stream/buffer.

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#174]
The current implementation does not distinguish error response to success response, resulting in the possible cases where the customer's input buffer/stream (when it's ready) is corrupted with error response from service, not actual customer data.

My proposal is to have another memory stream that is used solely for the response body when errored out. The client can choose which information should be parsed from this stream. This way, customers do not need to worry about unexpected response body corrupting their input stream/buffer.

**Comment by gilbertw** [comment]
@JeffreyRichter I expect we would throw a RequestFailedException in these situations.  Does that match your design?  If so this is pending work we have in the pipeline.

**Comment by JeffreyRichter** [comment]
I think the best approach is this: when the transport adapter sees a non 2xx HTTP status code, it always reads the response into a body buffer instead of a body stream. At the top of the pipeline, the convenience layer code can see the status code and if not 2xx, then parse the body buffer and handle the error as it desires. This MIGHT mean that the convenience layer decides to throw a RequestFailedException but this part of the flow (what to do about the error) is NOT an Azure Core issue.

**Comment by gilbertw** [comment]
The [SDK general guidance](https://azure.github.io/azure-sdk/general_implementation.html)s says throw or return error if a request fails.  Our [guideline](https://azure.github.io/azure-sdk/general_implementation.html)s say C++ throws on recoverable error.  The guidelines are not clear on if/when Core throws.  I expect Core behaves like clients and throws.

**Comment by JeffreyRichter** [comment]
Well, for some failure HTTP status codes, the pipeline will retry and NOT throw an exception. So, whether something is an error or not is in the eye of the caller. The pipeline should do little interpretation of the response. Some pipeline policies (like retry) will interpret it and the convenience layer will interpret it. If the transport or other policies interpret the response then it adversely affects any other interpretations that might want to happen higher up the stack. The best interpretation is best done in a domain-specific way and the client library has the most domain-specific knowledge as to exactly what operation was being performed and what the semantic meaning of this operation is. So, I think it best if we leave the bulk of the interpretations up to the client library. 

Here's a real-life, concrete example: Some Blob client libraries offer a CreateContainerIfNotExists function. This function tries to create a blob container. If the container already exists, then the service will return an error BUT, the function should NOT throw in this case. Because the FUNCTION (not the service operation) is successful even if the service operation fails.

**Comment by gilbertw** [comment]
Storage is not a good gold standard for us to go on.  Its expected the service will return 500 in some scenarios.  
`
CannotVerifyCopySource | Internal Server Error (500) | Could not verify the copy source within the specified time. Examine the HTTP status code and message for more information about the failure.
-- | -- | --

`
That's a really bad "expected" error to have occur.
However I can see based on various service return codes that we will not be able to determine success/failure.  We will need to consider a non-200 result as failure.  In that model returning the body into the bodybuffer seems reasonable.

**Comment by vhvb1989** [comment]
@katmsft whenever we send a request and an error is returned (statusCode >= 300) the error is all read from the wire and written into the body buffer inside the request (std::vector)

protocol layer can check the rawResponse returned from `send()` for the statusCode.

I believe storage team is already doing this.
Can you mention if we can close this one?

**Comment by vhvb1989** [comment]
@katmsft  I am closing this one for now and as per previous explanation.
Please re-open if there is something else to be done for this issue
