### ISSUE TITLE
Remove the ValuePolicy from Azure Core

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1767]
Consider refactoring any sdk client using this policy.

One of the reasons why this Policy exists is based on the protocol implementation of a service where the API operations don't have access to the client options.

For example, imagine we create client `A` with client options : `{ version: 1.0 }`
The clientOptions is a member inside A.
Then, when we call `A.Foo()`,  This api method have access to the client options, but, instead of creating the `HttpRequest ` before calling the protocol layer, we delegate creating the `HttpRequest` to the protocol layer. After creating the `HttpRequest` we need to add a header to it with the `version` from the client options. `request.AddHeader("version", clientOptions.version);` 

So we call `ProtocolLayer.Foo()` and at this point, we don't have access anymore to the clientOptions unless:
- The protocol layer requires clientOptions const& in constructor to be init.
- All methods from the protocol layer would take clientOptions as const&
- The sdk client expose an static method to create a based `HttpRequest` that is used for all of its methods (taking only the method and path as input). Then the protocol layer can use it to construct an HttpRequest.

No other language is using something like a valuePolicy instead of manually setting the HttpRequest  headers.  In C++ we are creating this policy to make a current implementation of a protocol layer to work, instead of updating the implementation to work without it.

**Comment by JeffreyRichter** [comment]
I think we want to keep this in Core as Internal.
The one usage we have for it today is to support the customer changing the API version used when talking to the service - all client libraries will require this.

**Comment by vhvb1989** [comment]
> I think we want to keep this in Core as Internal.
> The one usage we have for it today is to support the customer changing the API version used when talking to the service - all client libraries will require this.

No other language need this policy for the same problem.  
The C++ keyvault service does not use it or need it.
There are many ways to implement the convince and protocol layer from sdk services to not depend on a value policy like the one we are trying to keep.

**Comment by JeffreyRichter** [comment]
KeyVault will need this too. If you look at https://docs.microsoft.com/en-us/rest/api/keyvault/createkey/createkey, you see api-version=7.1. When they add another version (like 7.2), then this functionality will be required.
You are correct that other languages do not do this this way they require that each client have customer code IN EACH OPERATION METHOD to change the api-version. Our C++ way via this policy means that it can be set by a client at constructor time and then none of the operation methods have to do anything ever again. So, our way is just better and other languages may change to our implementation. 

If you think we really don't need this, then what do clients need to do to support changing the api-version?

**Comment by vhvb1989** [comment]
All we need is operation methods to have access to the client options.
Some ways to make this:
- Factory pattern in service-common-package `Request InitServiceRequest(clientOptions)`. This will ensure a single common place for creating a request for all packages from the service. Instead of setting this per each client pipeline, all method operations just calls the `InitServiceRequest`. Usually it is the protocol layer the one in charge of creating the request, so, API methods don't really know how to create a request, they can only pass the clientOptions reference for all the protocol implementation, and from there, we can call the factory.
- The service can create a derived class from HttpRequest named something like `<ServiceName>Request`.  Make this derived class to take `serviceClientOptions` in the constructor. Then API methods use this class to get an HttpRequest which will be init in construction time with the service-specific headers/query in it.


Here are some of the reasons why the all-purpose-policy (a.k.a. the valuePolicy) can be problematic:
- How do I document or keep track of all the things that I am setting with this policy?  Imagine there's a bug while setting a header named `myCoolHeader`, how do can I have an easy mental model about `myCoolHeader` is set on the ValuePolicy, similar to the same mental model of requestId is set on requestIdPolicy, or the other policies. I might need to do a global search in the project for `myCoolHeader` to discover where it is being added.
- Debugging can become also hard if this policy overrides another single-purspose-policy.
- Naming the policy has been a challenge since the beginning, this have to be an early signal of the complexity and confusion this policy will keep around.
- If at some point we want to support this valuePolicy reacting to a Context for per-call-settings (like sending one API method to one service version just one time), we could end up with a n-square function which needs to loop all the headers and queries from the valuePolicy and then traverse the Context nodes to see if the value is in there.  This is because not even the ValuePolicy knows about what headers or queries it will set.  Compared to having having only specific one-single-purpose policies where we can choose which one can be overridden per-operation.

**Comment by Jinming-Hu** [comment]
> All we need is operation methods to have access to the client options.
> Some ways to make this:
> 
> * Factory pattern in service-common-package `Request InitServiceRequest(clientOptions)`. This will ensure a single common place for creating a request for all packages from the service. Instead of setting this per each client pipeline, all method operations just calls the `InitServiceRequest`. Usually it is the protocol layer the one in charge of creating the request, so, API methods don't really know how to create a request, they can only pass the clientOptions reference for all the protocol implementation, and from there, we can call the factory.
> * The service can create a derived class from HttpRequest named something like `<ServiceName>Request`.  Make this derived class to take `serviceClientOptions` in the constructor. Then API methods use this class to get an HttpRequest which will be init in construction time with the service-specific headers/query in it.
> 


Maybe it's just my personal opinion, but I hate everything about inheritance. My design principle is "simplicity over complexity". Your proposal looks too complicated, over-abstracted and I don't think it's worth it at all.

if you google "inheritance abuse/anit-pattern/bad practice", you'll find i'm not the only one who doesn't like it. From my perspective, the only reasonable use of inheritance in this SDK is `BodyStream`. The inheritance hierarchy of pipeline/policy is the root of all evils. (`ValuePolicy` we're discussing in this issue is one of the evil consequences). Other evil consequences including:

* We have to define a new class to derive from base HttpPolicy, and come up with a good name for this new class. Which makes us have to face one of the two hard things in computer science.
* We have to define constructor for this new class
* HttpPolicy is not copiable because of polynomial, so we have to define a `Clone()` function.
* Still because of polynomial, pipeline cannot just be a vector of HttpPolicies, it has to be a vector of HttpPolicy pointers.
* All above makes it expensive to define new HttpPolicy. But unfortunately we do have needs to add various HTTP headers to request. Then here comes this `ValuePolicy`, which is different from all other policies because every other policy has a specific purpose. But this `ValuePolicy` is too generic and some people don't like it (me and I guess also Victor).

We could've made things easier by defining pipeline as `std::vector<std::function<RawResponse(Context, Request&, NextHttpPolicy)>>>`, a vector of function objects that accept `Context`, `Request` as parameters and return raw response. Then all above issues are solved. Defining a new policy can be as easy as

```C++
auto serviceVersionPolicy = [](Context context, Request& req, NextHttpPolicy nextPolicy) {
    req.AddHeader("x-ms-version", "2020-02-10");
    return nextPolicy(context, req, next + 1);
};
```

But we've gone too far on the inheritance road and I guess cannot come back anymore.

**Comment by vhvb1989** [comment]
After talking to @JeffreyRichter , we decided this policy won't be exposed by Core.
Storage can host it and use it.
I will create a PR for Apr release to make the change. (It is not a breaking public change)

**Comment by Jinming-Hu** [comment]
@vhvb1989 I'm gonna make a PR removing the use of this Policy, so that you can remove it.

**Comment by vhvb1989** [comment]
I am taking this issue as soon as #1914 is merged
