### ISSUE TITLE
Namespace organization

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1789]
Move the types in azure-core package based on feedback and discussions with archboard members.

### Service Namespaces
Services are under top level `Azure::`.  Core is grouped as "service" to avoid cluttering the toplevel namespace.
`Azure::Storage::....`
`Azure::Security::...`
`Azure::Security::KeyVault::...`

azure-core is treated as a service for grouping purposes.  The types under Azure::Core are less commonly used types by customers and should be grouped according to their purpose.

`Azure::Core::Http`
`Azure::Core::Cryptography`

#### No non-service top level namespaces allowed
Toplevel namespaces are reserved for services.  This prevents us from using a namespace that could at some point become an azure service.  It also helps with discoverability.  Customers looked for advanced azure-core functionality can begin their search in `Azure::Core`.

//Valid
`Azure::Core::Http`
`Azure::Core::Cryptography`
`Azure::Core::Diagnostics`

//Invalid
`Azure::Http`
`Azure::Cryptography`
`Azure::Diagnostics`
`Azure::Utilities`

#### Detail namespaces
The detail namespace is implementation that is internal to the package (i.e. service).  These are implementation details and can change at any time without notice.  
DO NOT expose `::_detail` namespace to customers in public headers or return types.  Where possible the _detail namespaces should reside in private headers.  
Each package can define _detail namespace(s) as they see fit under one condition.  The _detail namespace must be the last namespace in the namespace chain.

Example:
`<service>::<somenamespace>::_detail` is valid

`<service>::_detail::<somenamespace>::` is invalid

//Top level _detail is NOT allowed
`Azure::_detail`     //Invalid

//Azure::<service>::<namespace>::<?_detail>
`Azure::Core::_detail`
'Azure::Storage::Blobs::_detail`
'Azure::Storage::Blobs::Model::_detail`

#### Internal namespaces
The internal namespace in `azure-core` denotes types that are used by service client libraries.  These types are not intended for use by external customers.  AzureCore reserves the right to break these types at any point in time.

Be consistent with detail and chain _internal at the end.

//Top level internal namespace is NOT allowed
`Azure::_internal`  //Invalid

#### Utility and Common namespaces
Packages should avoid Utility (or similarly purposed) namespaces.  These are prone to become grabbag dumping grounds.  Types should instead be placed into the most relevant namespace for the type.  If you are unsure of where a type should reside reach out to the team to discuss.

//Invalid
`Azure::Core::Utilities`

### Types in Azure vs Azure::....
https://microsoft-my.sharepoint.com/:x:/p/vivazqu/EQ2-zpjm_a9IgLHyhHRAenIBstAHk0SdEJfIIVqqm1Tk4w?e=tInIln

**Comment by RickWinter** [comment]
cc @JeffreyRichter

**Comment by ahsonkhan** [comment]
**I support `HttpRange` renaming.** We shouldn't have Method, StatusCode, or Range. The way to reason about this is chances of collision and ease of documentation/discover-ability in SEO. RawResponse is specific enough that it doesn't need Http prefix, that's how I would draw the line.

**We should move `RequestFailedException` to root Azure**, and not change things about it, and definitely not use `TransportException` as a replacement. 

Since all our policies and the pipeline are supposed to be internal, we shouldn't have a sub-namespace for these. **Leave them at `Http::_internal`. The base class `HttpPolicy` can live in `Http::`**

**Don't have `Azure::Core::Security`, keep `Azure::Core::Cryptography`.** And then we need to find a home for `Credential`, move it/keep it in `Azure::Core`.

**Comment by JeffreyRichter** [comment]
ETag, MatchConditions, ModifiedConditions, and Response are all http-specific, I think they should be in the HTTP namespace.
They are meaningless for non-HTTP services like EventHub or ServiceBus (AMQP) or IoT (MQTT).

DateTime is in Azure but String, Uuid, URL, Version are in Azure::Core? Seems arbitrary to me. There is no way a customer will grok this. 

Also, we have many public functions that take Context and so customers will need Azure (for DateTime), and Azure:Core (for Context, String etc.). For critical types, why should customers need these 2 namespaces all the time?

RequestFailedException is also specific to HTTP.

I think BodyStream should remain in Azure::IO because most services (like KeyVault) will not use it at all and this type (and derived types) should only appear via intellisense when the customer is using a service that needs them.

I think Azure::Core::Http::Policies is better than Azure::Core::Http::Pipeline because the term pipeline is not really visible to customers but they see the policy and their options.

The Credentials type should be in Azure::Core::Http because it is specific to HTTP.

I like Azure::Core::Cryptography for the hashing types.

I do not think that logging requires its own namespace at all and Azure or Azure::Core is good enough. There is only 1 class publicly exposed called Log.

**Comment by ahsonkhan** [comment]
> ETag, MatchConditions, ModifiedConditions, and Response are all http-specific, I think they should be in the HTTP namespace.
> RequestFailedException is also specific to HTTP.

That's true. However, from a usability/discoverability perspective, we wanted to raise the visibility of certain very commonly used types to the root `Azure` namespace. For example, almost all client library APIs return a `Response<T>`.

> DateTime is in Azure but String, Uuid, URL, Version are in Azure::Core? Seems arbitrary to me. There is no way a customer will grok this.

The `Strings` namespace is not about a string type, but rather some string helper methods like ToLower/etc. Do you have a suggestion for this?
Similarly, `Version` is being renamed to PackageVersion and that needs to stay in the package-specific namespace.

Uuid and URL could be part of the root namespace if you think these will be as common as the other types there. I argue they aren't as common, and there is value to be selective on what we put in the root namespace to avoid making it too noisy, leaving room for the SDK to grow in the future.

> I think BodyStream should remain in Azure::IO because most services (like KeyVault) will not use it at all and this type (and derived types) should only appear via intellisense when the customer is using a service that needs them.

Isn't bodystream used from all client libraries when returning a response back to the user? Are you suggesting that many client library APIs won't accept **as input** a boydstream type? In that case, this suggestion makes sense. Though we had decided to keep the `::Core` sub-namespace for all things from azure-core.

> I think Azure::Core::Http::Policies is better than Azure::Core::Http::Pipeline because the term pipeline is not really visible to customers but they see the policy and their options.

`+1`, although I question us even having such a sub-namespace if the only public type it will contain is `HttpPolicy`.

> I do not think that logging requires its own namespace at all and Azure or Azure::Core is good enough. There is only 1 class publicly exposed called Log.

Do we expect the logging/diagnostic feature set to grow in the future? Where would we place types that support distributed tracing?

**Comment by JeffreyRichter** [comment]
If we do an EventHubs or ServiceBus client library, then Response<T> will NOT be used at all and having the HTTP types in the Azure namespace is just noise now for types that will never be used.

The Strings functions (ToLower/etc.) I would not expose to customers at all. But, if we really need to for some reason, then put them on the Convert class?

I'm not on board with the "common for customers to use argument". What is common for one customer is uncommon for another customer. For example, the EventHub customer doesn't use any HTTP stuff at all.  So, I'd put in Azure namespace what is useful to any service. "Common" is an arbitrary judgement call. So Uuid & Version should be in common because they are useful to many (or all) services.

BodyStream is only exposed to users when uploading/downloading bytes. Except for Storage almost no services do this at all; they read the stream and deserialize into a structure and the customer gets the structure - not the stream.  Azure::Core:IO is a fine namespace.

The Option structs will also be in the Polic namespace

Distributed tracing has no relationship to logging. I do not expect the logging feature set to grow.

**Comment by ahsonkhan** [comment]
> If we do an EventHubs or ServiceBus client library, then Response will NOT be used at all and having the HTTP types in the Azure namespace is just noise now for types that will never be used.

Imo, some service SDKs not needing it is fine. Other languages have made that decision to highlight types like `Response<T>` even when not used by **all** services. I think the set of APIs/types used by **all** will be low (maybe even zero).

It remains useful to expose some SDK types at the root, following a guideline like this:
**Any type that is heavily used as an exchange type (or expected to be) within two or more service client libraries, particularly in mainline scenarios, should be elevated to the `Azure::` root namespace.**

> "Common" is an arbitrary judgement call.

I somewhat agree, but its our responsibility to make those judgement calls based on intended usage. Human judgement on things like this (similar to naming) is part of the problem domain.

> But, if we really need to for some reason, then put them on the Convert class?

If we happen to make them public (which they currently aren't) and put them in a Convert class, do you recommend that class be in the `Azure::Core` namespace?

> Distributed tracing has no relationship to logging. I do not expect the logging feature set to grow.

The intention of a Azure::Core::Diagnostics namespace was to put anything related to diagnostics in there, which includes logging today but might include distributed tracing tomorrow. What namespace would you put types to support distributed tracing tomorrow?
We also might grow to introduce some loggers other than one that outputs to console.

**Comment by JeffreyRichter** [comment]
So, let me ask you: Is the Convert class common enough to be in Azure or Azure:Core?

Distributed tracing is done via a pipeline policy so I would put the policy's option structure in our HTTP namespace.

If we have some default loggers, then they can be in a logging namespace or, then can be nested in the Log class. To me logging is important to customers to detect problems at test AND deployment time so I think it better to elevate its visibility.

**Comment by ahsonkhan** [comment]
This has been resolved.

@RickWinter the next steps are to update the guidelines with some of the conclusions we reached from this discussion, which I will leave it up to you to decide how to track that change (maybe issue in azure-sdk repo).
