### ISSUE TITLE
WinHttpTransport GetRawResponse should be ExtractRawResponse

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#1804]
The private member is taking the raw response so it should be Extract since it takes over ownership of the memory.

    std::unique_ptr<RawResponse> GetRawResponse(
        std::unique_ptr<Details::HandleManager> handleManager,
        HttpMethod requestMethod);

**Comment by ahsonkhan** [comment]
I don't understand what you mean here about taking ownership.

The `GetRawResponse` method in the transport talks to the azure service and creates a `RawResponse` object to give to the caller. I don't think extract makes sense in this case.

Since the transport adapter's Send method is creating the object from scratch and giving it as unique ptr to the caller, the current name seems fine to me (especially since its private).

**Comment by vhvb1989** [comment]
Based on what you mentioned @ahsonkhan , it would be better to name it `Send()`  or `OnSend()`.
Even though it is private, it end up being misleading because we use `Get....()` for method on containers or wrappers like Response<T>, Operation<T>, Request, etc.  Containers which would return a copy or reference to its encapsulated state or Extract...() to give up state.

Would you agree on updating the name to `OnSend()` or something else?  

I agree with you about `Extract` does not make sense for Transport since it's not a container, but Get... is also not a good name

**Comment by ahsonkhan** [comment]
Given this has little to no material impact (or benefit) to the end user, I am fine with whatever name folks feel fits best here (something like `SendRequestAndGetResponse()`). I am also OK with leaving it as is and closing the issue.

Given the priority of other, more important, changes, moving to backlog.
