### ISSUE TITLE
Is it feasible to typedef Nullable<T> to mirror Optional<T> when the user application supports C++17 or above.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1816]
Consider using typedefs to treat `Nullable<T>` as `optional<T>` when the user application does support C++17, even though the SDK targets C++14.
https://en.cppreference.com/w/cpp/utility/optional

Our nullable type is very similar to optional, so I am wondering if this is feasible without the calling code be broken regardless of what language version the user references.

cc @antkmsft, @RickWinter, @CaseyCarter, @JeffreyRichter

**Comment by CaseyCarter** [comment]
The type switching is fairly trivial to do absent any concerns about ABI compatibility - we simply need to arrange for `nullable.hpp` to only define a template alias:
```c++
namespace Azure::Core {
  template <class T>
  using Nullable = std::optional<T>;
}
```
when compiling in C++17-or-later modes. Note that doing so violates the One Definition Rule if a binary is composed of translation units that are not all compiled in the same language mode. Such an ODR violation will produce horrible runtime bugs unless the layout of our `Nullable<T>` miraculously happens to exactly match the layout of the standard library's `optional<T>` and the implementation isn't particularly perverse.

We don't provide ABI stability from release to release, but I do think we should provide ABI stability for the same release across language versions. I believe this is the most common policy for C++ libraries - certainly the thee major Standard Library implementations I'm familiar with - but it's not universal.

**Comment by ahsonkhan** [comment]
>  if a binary is composed of translation units that are not all compiled in the same language mode

How common is that in practice?

> Such an ODR violation will produce horrible runtime bugs unless the layout of our `Nullable<T>` miraculously happens to exactly match the layout of the standard library's `optional<T>` and the implementation isn't particularly perverse.

Right, I don't think we can make `Nullable<T>` match the layout of `optional<T>`.

> We don't provide ABI stability from release to release, but I do think we should provide ABI stability for the same release across language versions. 

I don't follow what you are recommending here. Are you suggesting we don't support this type switching even though we are not promising ABI compatibility with the SDK?

**Comment by CaseyCarter** [comment]
> > if a binary is composed of translation units that are not all compiled in the same language mode
> 
> How common is that in practice?

I don't have telemetry, but in general I believe it's fairly common. C++ programs that grow large enough accrete library dependencies, and those libraries are often built with their own particular configuration and statically linked to sidestep DLLs completely. Given our lack of ABI stability guarantees, it may be reasonable for us to document that all client code that interacts with Azure SDKs must be compiled with the same language mode. (Aside: I'm under the impression that the SDKs are all header-only libraries but I now realize I've never validated my belief. Are they in fact header-only?) Note that admitting this kind of type-switching into the design is effectively a commitment that at least the parts of the library that need to interact with the subject types will always be header-only.

> > We don't provide ABI stability from release to release, but I do think we should provide ABI stability for the same release across language versions.
> 
> I don't follow what you are recommending here. Are you suggesting we don't support this type switching even though we are not promising ABI compatibility with the SDK?

That is what I was suggesting here, but with more reflection about how I expect the SDKs to be used I'm now back on the fence. I've done type-switching like this in the past with borderline research libraries like range-v3, but never in a library with commercial support guarantees and a hardline policy against source-breaking changes like the Azure SDKs. If we're comfortable with potentially telling a customer that they shouldn't have added a binary dependency because the SDK doesn't provide ABI compatibility and they'll need to get that dependency recompiled to match a change in language mode, then I think we should be fine.

**Comment by vhvb1989** [comment]
@ahsonkhan consider closing this issue as per Rick's comment

**Comment by ahsonkhan** [comment]
Discussed offline with Casey.

C++ exposes the object layout and hence trying to typedef `Nullable<T>` as `Optional<T>` for certain language versions will not work and can cause customer applications to get undefined behavior.

If an application developer references two third party libraries that were themselves built using different version of the language, and which both referenced the Azure SDK, there will not be a unified representation of `Nullable<T>` for the application developer to use, which is not the experience we want.

Additionally, the SDK is meant to work cross-platform, and even if we match the object layout of `Optional<T>` for a particular platform, it may not match on others, and hence break customers.

Therefore, closing the issue as by design.
