### ISSUE TITLE
Unify the interface of Response<T>::GetRawResponse and Operation<T>::GetRawResponse

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1831]
https://github.com/Azure/azure-sdk-for-cpp/blob/8bf8ebb53c3a276278bcece002f50bb0f54b08fe/sdk/core/azure-core/inc/azure/core/operation.hpp#L59

https://github.com/Azure/azure-sdk-for-cpp/blob/8bf8ebb53c3a276278bcece002f50bb0f54b08fe/sdk/core/azure-core/inc/azure/core/response.hpp#L54

One returns pointer while the other returns reference, wouldn't it better if they're consistent?

**Comment by Jinming-Hu** [comment]
Another question is, would it make more sense if returning const reference?

**Comment by Jinming-Hu** [comment]
Another question is, should we have `ExtractRawResponse` for `Operation<T>`?

**Comment by ahsonkhan** [comment]
cc @RickWinter and @JeffreyRichter

**Comment by ahsonkhan** [comment]
Both types now return a reference, so they are consistent. The fix to make it const is being tracked separately by: https://github.com/Azure/azure-sdk-for-cpp/issues/1865
https://github.com/Azure/azure-sdk-for-cpp/blob/a8649822084ffa518484c31870986306d404f240/sdk/core/azure-core/inc/azure/core/operation.hpp#L97
https://github.com/Azure/azure-sdk-for-cpp/blob/a8649822084ffa518484c31870986306d404f240/sdk/core/azure-core/inc/azure/core/response.hpp#L55

Fixed in https://github.com/Azure/azure-sdk-for-cpp/pull/1875

Hence, closing.
