### ISSUE TITLE
[Datalake][HowTo] - Increase upload chunk size when calling Append method

### ISSUE THREAD

**Issue by ysriram-adobe** [Azure/azure-sdk-for-cpp#2016]
**Query/Question**
How to increase the upload chunk size when calling `datalake_file_client::Append` method. It is currently defaulted to `1024*64 bytes` here `https://github.com/Azure/azure-sdk-for-cpp/blob/0665efe0fea59e201e3b0bac040ef7da978a5e35/sdk/core/azure-core/src/http/curl/curl.cpp#L413` .

***Why is this not a Bug or a feature Request?***
Maybe the the request option need to be exposed ?

**Setup (please complete the following information if applicable):**
 - OS: MacOS Catalina 10.15.6
 - IDE : vsCode
 - Version of the Library used: azure-sdk-for-cpp-azure-storage-files-datalake_12.0.0-beta.8
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by ahsonkhan** [comment]
@ysriram-adobe I am curious to learn more about your scenario. What are you trying to do exactly?
Also, why do you want to increase the upload chunk size, and what value would you want to set it to?

**Comment by ysriram-adobe** [comment]
@ahsonkhan - Trying a POC involving apache-arrow that requires us to be able to process files in Azure/DL . When writing parquet blocks to ADL via arrow/parquet writer I would like to increase (or experiment with different payload sizes) the upload chunk size assuming that it will reduce over job latency. 

Is it even possible to increase it to 64Mb ? According to you what is the optimal sizing ?

**Comment by Jinming-Hu** [comment]
This is a question to transport layer. @vhvb1989 @ahsonkhan

**Comment by vhvb1989** [comment]
@ysriram-adobe we can increase the upload chunk size for uploading, but, at least for HTTPS, in the case of libcurl + openssl, the data will be encrypted in 64k chunks for transferring in the secure channel, so you might not notice a difference (unless we use HTTP).

I recently removed the support for the current transport adapters (libcurl and winhttp) to allow setting up the upload chunk size. Mostly because there was no mechanism to export this feature from public APIs.  I can re-enable this feature, but first I would ask @JeffreyRichter and @gilbertw how would we like to expose it and support it.  Here are the possible options:

- As client option abstraction.
Customers would see this option in the clientOptions.TransportAdapterOptions like `blobClientOptions.TransportAdapterOptions.uploadChunkSize`.   The setting would be the input for the TransportPolicy and latter passed to the transportAdapter.

- As a transport adapter specific option.
Each transport adapter would define how to support this feature and would use the TransportAdapterOptions to set it up.

- As per operation option.
Using the context to set the value for specific operations. This option could be implemented together with first option.

Anyway, if you want to start experimenting in your POC and see if it would work @ysriram-adobe I can provide instructions to build from source updating the default value in source for compiling with different values. That would help you to see if the feature would be helpful

**Comment by JeffreyRichter** [comment]
Let's let @ysriram-adobe experiment first and IF the experiments yield valuable results, then we can decide how to best expose this. Right now, the 64KB is a process-wide setting (that is not settable). My default stance would be to keep this a process-wide setting: maybe we just define this as a constant in the Curl transport adapter source code to make it easy for some customers to change it when compiling.

**Comment by ysriram-adobe** [comment]
@JeffreyRichter - agree with you, will change the setting in sdk/curl src and experiment. Will let channel know if there is actually any impact. Thank you.
