### ISSUE TITLE
Add tests for default policies constructed by ClientOptions not interfering with each other

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2027]
I am thinking we must have tests where we use all the default policies so we know how they work together.
Right now, we are testing policies individually, which is fine, but we won't catch issues of one policy corrupting or changing another policy's data.

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/2009#discussion_r605314094_

**Comment by vhvb1989** [comment]
Won't make it for April. Let's not add issues to the current milestone if there is only a few days left for code-complete.
Moving to backlog

**Comment by vhvb1989** [comment]
The transport adapter tests were recently updated to use the default HttpPipeline constructor ( see this: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/azure-core/test/ut/transport_adapter_base_test.hpp#L89 ). 

This constructor uses all Core-default policies.  So we are already covering what this issue is asking for. Closing.

@antkmsft  please re-open and comment if you thing there's still more to be done here
