### ISSUE TITLE
Add version to Perf package

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2086]
Add the version headers to the perf package just like all other packages

**Comment by ahsonkhan** [comment]
I don't quiet understand the use case and why we want to treat the perf framework as a package with its own version. I'll reach out offline to understand why we need to do this.

@vhvb1989 since the issue is marked `help wanted`, can you add a link to the existing version headers in your issue description to show an example of what type of fix you are looking for.

**Comment by RickWinter** [comment]
@gearama Is this bug still relevant?  If not can you close
