### ISSUE TITLE
How to create the Operation

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2146]
Need to close on using overload method.

Alternative: Use a constructor

**Comment by ahsonkhan** [comment]
One factor to consider when weighing the alternatives is how common the resume scenario is in comparison to the number of most important service client APIs:
https://github.com/Azure/azure-sdk-for-cpp/pull/2093#issuecomment-818332589

For example, if `KeyClient` only has a few key operations (createkey, getkey, deletekey, backup, update), then adding 2 more methods to support the less frequently used `StartDeleteKey` LRO (like Resume), might increase the noise to signal ratio when the customer looks at all the available client methods.

**Comment by vhvb1989** [comment]
# options comparison

## client method

Can be implemented as an API overload or as a new API which uses the same name as the API that creates the operation plus a `Resume` prefix. For example, an API like:
`StartDeleteKey` , there would be a `ResumeDeleteKey`.

Then new API with the prefix is required for the next reasons:
- There might be impossible to overload the original API just with one string as it might end up with the same signature where string is already used as the parameter.
- There might be confusing for customers to see the overload which takes the resumeToken for an API called `Start...`. They might think that a resumeToken is required to start the operation.

### How code looks

```cpp
auto operation = client.StartDeleteKey("keyName", context);
auto resumeToken = operation.GetResumeToken();
auto resumeOperation = client.ResumeDeleteKey(resumeToken, context);
```

### benefits
- Follows the SDK pattern for creating output models from client to end-users.
- Constructors from the Operation can be private. The model is expected to be created only by the SDK client to be consumed and as output.

### Cons
- Adding one extra method to the client for each start-operation-like API in the client.

## Operation Constructor

The `Operation<T>` can be init based on a resume token a a client

### How code looks

```cpp
auto operation = client.StartDeleteKey("keyName", context);
auto resumeToken = operation.GetResumeToken();
Operation<DeleteKeyOperation> resumeOperation(resumeToken, client);
```

### benefits
- Less noise for api methods which might be not super relevant.

### Cons
- End-user needs to know the operation type. In the previous code, I need to know about `DeleteKeyOperation` since I can't just use `auto` for all types like in the method-approach
- `Operation<T>` is exposed as a constructible object to customers. This will be the only model in the SDK that behaves like this or exposes this pattern.  So it's a new pattern/detail to be learned from customers

**Comment by vhvb1989** [comment]
@RickWinter  @JeffreyRichter  I have documented the different approaches.  Please let me know if you have questions about it.
Please make a decision for what we want for the SDK.

My vote goes for `client method` approach

**Comment by ahsonkhan** [comment]
To incorporate some of the usability learnings from .NET that @tg-msft shared, I prefer the operation ctor approach.

But to steel man the argument for the client method approach, @vhvb1989, the other con of the operation ctor approach is that the caller needs to explicitly call `poll` to rehydrate the operation fully. Whereas in option 1, that is done by the SDK. That might be considered both a good and a bad thing, good for usability (user has to write less code), but also does some more "magic" and reduces control users might want.

**Comment by JeffreyRichter** [comment]
First, I LOVE your presentation here showing the customer code - great job!
Second, I like the client method proposal better because it is more discoverable and because it follows our normal patterns; that is, customer usually start with a XxxClient and then do something with it. It feels unnatural to me to start with an Operation and pass its ctor a client; we have no other precedent for this pattern anywhere in the SDK that I can recall.

**Comment by ahsonkhan** [comment]
> First, I LOVE your presentation here showing the customer code - great job!

+1

>  I like the client method proposal better because it is more discoverable and because it follows our normal patterns; that is, customer usually start with a XxxClient and then do something with it

Do we really want these resumable APIs to be discoverable though? At the same level as the other more frequently used and important client APIs? To me, resuming polling **is** different than the other set of client APIs, so having a design and coding pattern that is different is a good thing. It doesn't start a new CRUD operation to change state of the resource on the cloud.

> It feels unnatural to me to start with an Operation and pass its ctor a client; we have no other precedent for this pattern anywhere in the SDK that I can recall.

We aren't starting with an Operation in either case though. The starting point is still the client.

**Comment by JeffreyRichter** [comment]
Operation's ctor could call Poll internally.
If the customer wants to use the "advanced & seldom used" resume feature, they need to get a token and then the either need to call a ResumeXxx method or construct an Operation.  I could live with either proposal. If this was usability tested in some language, I'm happy to use that data to help direct us.

**Comment by RickWinter** [comment]
I favor the method approach.  I question though the naming vs overloaded methods.  I would expect a DeleteKey method and a DeleteKey method with a token to allow continuing to poll.

```cpp
auto operation = client.DeleteKey("keyName", context);
auto resumeToken = operation.GetResumeToken();
auto resumeOperation = client.DeleteKey(resumeToken, context);
  //or
auto resumeOperation = client.DeleteKey("keyName", resumeToken, context);  //Key name is unnessecary if we put it in the resumeToken object
```

**Comment by vhvb1989** [comment]
After voting for an approach, the `using constructor` approach was decided to be the best option.
However, the constructor should not make I/O requests for getting the initial state and should also not throw.  

So, to solve this, a third option is proposed by using a factory method in the `Operation<T>` class which takes the resume token and the client and returns the `Operation<T>`. This method would init and call poll.

So, customer code is expected to be:
```cpp
auto operation = client.StartDeleteKey("keyName", context);
auto resumeToken = operation.GetResumeToken();
auto resumeOperation = DeleteKeyOperation::CreateFromResumeToken(resumeToken, client);
```

**Comment by ahsonkhan** [comment]
That approach sounds good to me, but can you please clarify why a factory method solves the problem that a regular ctor couldn't?

**Comment by vhvb1989** [comment]
> That approach sounds good to me, but can you please clarify why a factory method solves the problem that a regular ctor couldn't? What motivates the use of a factory method?

As a best practice, a ctor should not make I/O request and should be no-except.  
A static method can take of the I/O call plus any other error handling while we let the ctor for pure-init purpose

**Comment by ahsonkhan** [comment]
Oh, is that why we are making it a static factor method?

We should leave it as a ctor on `Operation<T>`, not make any I/O requests, and leave some of the state uninitialized, like what .NET does.

**Comment by ahsonkhan** [comment]
Based on offline discussion, the factory method that fully hydrates the `Operation<T>` is a good enough alternative, and leads to an object state that the customer can more easily reason about.
