### ISSUE TITLE
@JinmingHu-MSFT , is there a reason to have this memoryStream and the one from Azure::Core ?

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#215]
@JinmingHu-MSFT , is there a reason to have this memoryStream and the one from Azure::Core ?
I would say let's have just one

_Originally posted by @vhvb1989 in https://github.com/Azure/azure-sdk-for-cpp/pull/214/review_comment/create_

**Comment by JinmingHu-MSFT** [comment]
@vhvb1989 
1. The MemoryStream from Azure::Core makes a copy of the data. The MemoryStream from Storage doesn't. Sometimes the user provides a buffer and wants to upload the data in the buffer, there's no need to make a copy. While in protocol layer, Storage SDK constructs HTTP request body with XML data, we have to use Azure::Core::MemoryStream because otherwise, nobody can take the ownership of the request body.
2. Storage team needs to support parallel upload/download, but the MemoryStream from Azure::Core doesn't provide enough functionalities.

I'm okay if we just have one, but only if both above problems can be solved.

**Comment by JinmingHu-MSFT** [comment]
It's important for storage team to avoid that copy. Because otherwise, it'd make it completely impossible to upload a memory-mapped file if that file is larger than physical memory. (I don't mean storage team would do so, just want to have the option)

**Comment by JinmingHu-MSFT** [comment]
Since Core changed their implementation of `Azure::Core::MemoryBodyStream`, Storage code also removed `Azure::Storage::MemoryBodyStream`

https://github.com/Azure/azure-sdk-for-cpp/pull/236

**Comment by JinmingHu-MSFT** [comment]
I'll close this one once that PR is merged.
