### ISSUE TITLE
std::shared_timed_mutex breaks iOS compilation

### ISSUE THREAD

**Issue by dipidoo** [Azure/azure-sdk-for-cpp#2154]
https://github.com/Azure/azure-sdk-for-cpp/blob/308e5363adaa00ace2f06ff0f1a31747a0a28062/sdk/core/azure-core/src/logger.cpp#L16

Compiling this for iOS with `OSX_DEPLOYMENT_TARGET=9` yields the following error:

`error: 'shared_timed_mutex' is unavailable: introduced in iOS 10.0`

Using this from vcpkg, 1.0.0-beta.6 did not have this issue and seems to have been introduced by 1.0.0-beta.7.

**Comment by ahsonkhan** [comment]
@dipidoo I am curious to learn about how you are using the C++ SDK for iOS. What functionality and features do you use and what are you building? Also, what's keeping you on iOS 9, from both directions (i.e. why not iOS 10, or why not support an even lower platform like iOS 8). Can you provide some more of these details and background to help motivate the issue because we don't yet support the iOS user story for this C++ SDK.

Are you looking to communicate to Azure Storage, and have you explored the iOS specific SDK?
https://github.com/Azure/azure-sdk-for-ios/blob/master/sdk/storage/AzureStorageBlob/README.md

iOS 10.0 came out in 2016, so not supported older versions matches the releases of some of the [other platforms we support in our compat matrix](https://azure.github.io/azure-sdk/cpp_implementation.html#supported-platforms),

@antkmsft - this is an interesting side effect of our recent logging changes.

@RickWinter - I moved this into the may milestone, fyi, so you can help triage and adjust.

**Comment by antkmsft** [comment]
Quick random thoughts, shared_timed_mutex is C++14.
It can be replaced with the regular mutex, for some perf cost. Could be build option to do that.
Also it can be implemented manually.
