### ISSUE TITLE
Remove validations from Azure SDK clients

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2183]
Storage SDK client is validating the input options for some API operations like 
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-files-shares/src/share_file_client.cpp#L171
and
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-files-datalake/src/datalake_file_client.cpp#L382

This goes against the SDK guidelines.

If there's a bad user experience or issue by removing or not having a validation on the SDK client, an issue should be added for the Service.

Also, no other language is adding this validations.

**Comment by vhvb1989** [comment]
@RickWinter  @JeffreyRichter  FYI. I created the issue as mentioned in the sync meeting

**Comment by Jinming-Hu** [comment]
This is by-design behavior, it's to avoid some headers that customers can set, but will be ignored by storage service.

**Comment by vhvb1989** [comment]
Re-opening as this going against the guidelines and requires arch-board approval. 

Please bring this to the sync meeting or talk to @JeffreyRichter about it

**Comment by Jinming-Hu** [comment]
There's a `ContentHash` field in most data transfer APIs. Most of the APIs support both CRC64 and MD5, but few of them only support either CRC64 or MD5, not both. [Here](https://github.com/Azure/azure-sdk-for-cpp/blob/fcf75f80d1765a1111356feefc1e38593c53cd9f/sdk/storage/azure-storage-common/inc/azure/storage/common/storage_common.hpp#L40) is  the definition of `ContentHash`.

If a customer passes a CRC64 value to an API that only supports MD5, storage service will just ignore that value rather than return any error. This misleads the customer into thinking the data integrity is validated but actually it's not. We 're lying to customers.

The current solution in storage code is to add an assertion. If the customer provides a hash algorithm that's not supported by the API, we think of it as a precondition failure and crash.

@JeffreyRichter  Do you think the current implementation is fine? Or do you have any other suggestions?

**Comment by JeffreyRichter** [comment]
I would remove the client side validations because having them is against our guidelines, inconsistent with other language SDKs, and against "The Service is the Truth" (TM) philosophy. At some point, the service team needs to do the right thing and we can't/shouldn't have to "fix" these issues in all of the language SDKs. Some users don't use an SDK at all and just make raw HTTP calls - the service has to address this large set of customers too.

**Comment by Jinming-Hu** [comment]
> I would remove the client side validations because having them is against our guidelines, inconsistent with other language SDKs, and against "The Service is the Truth" (TM) philosophy. At some point, the service team needs to do the right thing and we can't/shouldn't have to "fix" these issues in all of the language SDKs. Some users don't use an SDK at all and just make raw HTTP calls - the service has to address this large set of customers too.

All right, I'm convinced.
