### ISSUE TITLE
FileDescriptors are exhausted

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2254]
Seeing a fd leak on large scale tests.

Per Jinming:

> Hi core sdk team, we recently found an fd leak issue during our large scale test, which will cause file descriptors to be exhausted after the process running for a few days.
> 
> I captured the fds opened by the process every 30 seconds, as we can see in the below graph. X-asix represents number of samplings. There are in total 659 samplings during 5.5 hours. Two kinds of fds kept increasing as time goes on, unix domain socket (purple line) and socket (pink line).
> 
>  
> 
> Maybe these two kinds of leak are related or maybe they are not. I investigated the unix domain socket leak as it looks worse. Typically unix domain socket can only be opened by two system calls, socketpair() and socket(AF_UNIX,). So I recorded all the system calls with strace. I found only socketpair() was called. Then I ran the program in gdb and set a breakpoint at SYSCALL 53 and got a stacktrace. It looks like the leak was in libcurl transport layer. I only found this issue on Linux but not on Windows. Maybe windows is not affected or maybe it’s just because Windows has a higher fd limit. Can you please help investigate this issue? Thanks.

Looks to be coming from
Azure::Core::Http::_detail::CurlConnectionPool::ExtractOrCreateCurlConnection

**Comment by vhvb1989** [comment]
The issue is in:
`sdk/storage/azure-storage-common/src/reliable_stream.cpp`:
https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/storage/azure-storage-common/src/reliable_stream.cpp#L39

When using the Reliable body stream, if there is a failure while reading from the network, the current code is calling `release()`:

```cpp
try
      {
        auto const readBytes = this->m_inner->Read(buffer, count, context);
        // update offset
        this->m_retryOffset += readBytes;
        return readBytes;
      }
      catch (std::runtime_error const& e)
      {
        // forget about the inner stream. We will need to request a new one
        // As m_inner is unique_pr, it will be destructed on reassignment (cleaning up network
        // session).
        this->m_inner.release();
        (void)e; // todo: maybe log the exception in the future?
        if (intent == this->m_options.MaxRetryRequests)
        {
          // max retry. End loop. Rethrow
          throw;
        }
      }
```

This causes the curl-session to be leaked. At any case, the expected call should be `reset()`, to call the dtor.  But calling release is just leaving the object in the head without a handler.

As a better, general practice, we should avoid calling reset() or release() to smart ptrs since we are losing the benefit of them and introducing this potential issues.

@Jinming-Hu, please remove the `release()` call, or replace it for `reset()` and try out your application. If you remove it, you need to adjust the logic to set the ptr to null, as I think you use it as a condition to request a new bodyStream...  that's why I am not creating a PR and leaving it to you to decide what to do.

The further explanation behind this issue is that it requires a failure to happen while reading a body stream which is more likely to happen on a 20TB download (the bigger the blob download is, the bigger chances to get a body-stream read failure)

This was an interesting issue, hard to debug. As a lesson learned I would ask again for not calling release()/reset() to unique ptrs as a guideline.  @RickWinter.  And review all other occurrences where there is a call to smart ptrs.Release() as a potential bug/leak.
