### ISSUE TITLE
What's the correct interface/behavior for Operation<T>::Poll and PollUntilDone

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#2314]
Hi @vhvb1989 , we discussed this a little bit in email but we didn't get a conclusion. So what's the plan now? Are we going to keep the interface unchanged or what?

**Comment by Jinming-Hu** [comment]
It doesn't affect storage code, so I'm fine with whatever.

@vhvb1989 Feel free to close this issue if you decide not to change anything.

**Comment by vhvb1989** [comment]
The operation T design was reviewed by Core team.  I follow up on the email @Jinming-Hu  started.

The decision is to keep the current approach as it is what brings the most of the benefits from the discussed proposals.  

@Jinming-Hu , Core team almost took your option of `poll not updating the internal raw response` but is has a problem when re-constructing an operationT from a `resumedToken` because the rawResponse from the Operation woould be null then.

Closing the issue as `keeping current design`
