### ISSUE TITLE
[eng/sys] Can I start all the release pipelines from one simple script?  

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2321]
@danieljurek  I would like to start Core, Identity, KeyVault, and  any other service release-pipeline, all with the same variables and by either running one command script or from from some WebUI.

It takes take to go to each pipeline and start it manually one by one. And it's not scalable as the services might keep growing.

Can you tell me how can we make this possible?  Maybe by running one of those magical scripts within the eng/scritps folder where I can pass the variables and it would do the job for me.  
The output of such script could be the link for each pipeline so I can later go and approve each one in any order I need (this can be still manual)

**Comment by kurtzeborn** [comment]
Victor, we could provide a script for this, but you'd still have to run the pre-release script for each library because of the library-specific questions that need to be answered (like which version to bump to) before release.  What exactly is the pain point here you're concerned about?  Is it that one person is releasing multiple libraries and it would be nice to be able to kick off all the pipelines at once?  Before we go forward on a solution, I want to make sure we understand the pain point accurately.

CC: @weshaggard

**Comment by vhvb1989** [comment]
Thank you @kurtzeborn,  For C++, I am currently starting 3 release pipelines (Core, Identity and KeyVault Keys)

This is typically the flow:

1. Run PrepareRelease script for each pipeline.  

Here I don't mind running the script for all pipelines. I even run for storage blobs, shares and files. This script updates the [work items](https://dev.azure.com/azure-sdk/Release/_queries/query/7d106acd-a1c2-47b9-9676-996422328397) for Cala and PMs scope.

2. Create and merge PR for changelog's date.

Set the date of the release in the changelog. The prepare script makes this job, yes!  But the Prepare script is run some days before releasing, so the changelog's date needs to be changed again anyway.

3. Run each release pipeline from the browser. (This is the most painful step!)

I need to browse to each internal pipeline like [the Core pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1615) and click on `Run Pipeline`. Then I need to manually add 2 release variables:
![image](https://user-images.githubusercontent.com/24213737/121097531-f859cd00-c7a8-11eb-8f07-11c325e15942.png)

And I currently repeat this step 3 times (one per pipeline).  What I am wishing for, is one script which can start the pipeline from the console. Then, I can run 3 commands from powerShell or something and skip all the WebBrowser interaction with Azure DevOps.

I would like to run something like:

```shell
Run_Pipeline azure-core variable-name=value variable-name2=value2
Run_Pipeline azure-identity variable-name=value variable-name2=value2
Run_Pipeline azure-security-keyvvault-keys variable-name=value variable-name2=value2
```

This would take me a few seconds instead of a few minutes from the UI


Let me know if this is helpful

**Comment by weshaggard** [comment]
@vhvb1989 @danieljurek is the only reason you need to pass variables is to share the same branch name for all the releases? Or is there some other variables that you are setting? Is there some way we can default those so that it becomes easier to queue without needing to set any variables. 

Regardless of how we queue the builds you will still need to go to each of the builds and then verify them and approve the releases for publishing so there will still need to be some interaction with-in the DevOps UI. So perhaps all that is needed is some way to ensure the pipelines are connected with the same default variables.

As for the Prepare-Release script it should stamp in the release day in the changelog when you run but if for some reason that isn't the correct date then you can pass in the date to the Prepare-Release script for which day you are planning to release. So you hopefully shouldn't need to update the date in the changelog multiple times. If there are still scenarios where you think that is needed I'd be interested in understanding them more.

**Comment by kurtzeborn** [comment]
@vhvb1989 Just following up on this.  We want to make sure we have the requirements right before we do anything here, so please respond to @weshaggard.  @benbp had some ideas to ease this repetitiveness, so please help us figure out the right thing to do here.

**Comment by vhvb1989** [comment]
>  is the only reason you need to pass variables is to share the same branch name for all the releases?

yes, the variables we need to set are currently 2. branch-name and PR title.

> is there some other variables that you are setting?

No

> Is there some way we can default those so that it becomes easier to queue without needing to set any variables.?

I would default it to some unique-per-release value like `azure-sdk-for-cpp-[release-date]` for the branch name and `Azure SDK for C++ [Release month]` for the PR name.  But we still need to be able to override the default value in case we want one service to create its own branch and not use the default.

> you will still need to go to each of the builds and then verify them and approve the releases for publishing...

Yes, but I would except the script to console-out the pipeline url so I can just click it and open the pipeline and wait to approve.  What I would really like to save myself is from manually browsing to each service's pipeline and manually clicking a button to start the pipeline (The less mouse-usage, the better). 

> As for the Prepare-Release script it should stamp in the release day in the changelog when you run but if for some reason that isn't the correct date then you can pass in the date to the Prepare-Release script for which day you are planning to release.

Last time I tried it did not work,  I will try it again setting the future day for the changelog and see if it works.


The real expectation here, and what I would love the most, is to reduce the UI interaction with a browser to Azure DevOps. Similarly how you help to reduce the pain of using the WebUI to update the workItems for each release by just using one script.

@weshaggard @kurtzeborn FYI

**Comment by weshaggard** [comment]
Completely understand about trying to reduce the number of clicks and thus the number of possible failure cases. Lets start by trying to provide intelligent defaults for the common scenarios. @danieljurek is there any good way to setup the default branches in a reasonable way? Or should we just create a wrapper script to handle the querying of these builds?

We already have some helper scripts that queue builds from the command line and it shouldn't be too difficult to wrap those for whatever scenarios are interesting for c++.
