### ISSUE TITLE
Vcpkg CI does not run daily

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#2328]
https://github.com/microsoft/vcpkg/pull/17119 does not seem to get upated on a daily basis.
And also the last time it was updated, it did not push changes for core for some reason, which resulted in PR failing.

**Comment by danieljurek** [comment]
In the case of circa May 19th there is a [build failure on May 17th for `cpp - core`](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=898687&view=results). This is the only build that would've pushed a change during the `Integration` stage but, since the build failed, no push was made. Ironically this failed because of a cache step by the name of `vcpkg` timing out after 10 minutes (ironic because both steps have `vcpkg` in the name but failures are unrelated). The `vcpkg cache` step taking this long is generally a product of networking errors on the DevOps VM. Re-running the pipeline will generally fix this issue. 

C++ pipelines for services (e.g. core, storage, identity, etc.) are scheduled to run daily before the `cpp - vcpkg-daily` pipeline which runs just before UTC midnight (23:15 UTC time).


There has also been mention of GitHub not showing the full history of pushes to the `release/azure-sdk-for-cpp-daily-verification` branch: 

Rather than have a diverging branch with a long history, the `azure-sdk:release/azure-sdk-for-cpp-daily-verification` branch is updated to point to the head of a daily branch. A side effect of this is that we have to force push the `azure-sdk:release/azure-sdk-for-cpp-daily-verification` branch every day and GitHub doesn't show the full history of the force pushes; it only shows the state of the branch at that time.

**Comment by danieljurek** [comment]
The `cpp - vcpkg-daily` pipeline is running according to its daily schedule. I think we can close this issue.
