### ISSUE TITLE
`pread()` may return `-1` on error.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#237]
What does a File Stream should do if Read file returns error?

**Comment by JeffreyRichter** [comment]
If pread returns -1, throw some kind of FileIO exception (talk to Casey) and maybe we put errno inside the exception object.
If ReadFile returns false, call GetLastError. If this returns ERROR_HANDLE_EOF, then return # bytes read; else throw the same fileIO exception and maybe we put the GetLastError number in it. 

The problem is that the errno/GetLastError number is OS specific so it's helpful to the developer when debugging but it's hard for the developer-customer to write code that checks the number and causes a special code path to execute.
