### ISSUE TITLE
Adding content type and accept to the request header should be per-operation rather than for all operations.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2541]
We are always sending these, even for GET or DELETE operations:
https://github.com/Azure/azure-sdk-for-cpp/blob/d0ca42643f4c81261ecaa8ba0d75ceb7d3127a48/sdk/keyvault/azure-security-keyvault-common/src/keyvault_pipeline.cpp#L33-L38

The approach works today because of the current service behavior for all existing operations.
This might cause future service changes to result in the client SDK to be broken.

**Comment by Jinming-Hu** [comment]
This isn't right. We shouldn't do this in a pipeline.

**Comment by vhvb1989** [comment]
> This isn't right. We shouldn't do this in a pipeline.

@Jinming-Hu , the KeyVault pipeline is a wrapper for the AzureCore main pipeline. It handles creating a request and starting the azure core pipeline.  It is the equivalent to the protocol layer from Storage.  So, the header is not set in "the pipeline".  The keyvault pipeline creates the request, then set the headers and then calls "the pipeline" from the sdk client.

KeyVaultPipeline is an implementation concept that connects the sdk client's pipeline with the protocol layer (since key vault is not auto generated)

**Comment by vhvb1989** [comment]
.NET is adding the content type as Json by default. @heaths , can we be sure that KeyVault will never add some API with a different content type? 

https://github.com/Azure/azure-sdk-for-net/blob/fbfd4eb8ed728a42f3b823f9ccd7c6a9cbb65d2c/sdk/keyvault/Azure.Security.KeyVault.Shared/src/KeyVaultPipeline.cs#L62

**Comment by heaths** [comment]
It's all JSON right now. If one day that changes - which is unlikely - we'll refactor the code accordingly e.g. defaulting to JSON with the ability to override. IMO, it doesn't seem worth refactoring now and duplicating code in each and every call in the unlikely chance one day it might possibly change.

Generated code may duplicate code like this by default, but it's generated. If the generated is updated, all the generated code is updated anyway. I don't see how it's worth duplicating in hand-written code right now for something that will likely never happen.
