### ISSUE TITLE
Getting terminate called after throwing an instance of 'Azure::Core::Http::TransportException' on Blob Download on Concurrent execution.

### ISSUE THREAD

**Issue by vivek-kumar-Niel** [Azure/azure-sdk-for-cpp#2802]
while testing the performance of blob download on offset range, getting this error almost always and we have to start our process again , which kills our application performance.

terminate called after throwing an instance of 'Azure::Core::Http::TransportException'
  what():  Fail to get a new connection for: httpsxxxxxxxxxxxx.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)

**testing 1 mb download over the 100 mb , 156 files in set of 10+ threads.**

    std::atomic<int> counter(numBlobs);
    std::atomic<int> ms(0);
    auto threadFunc = [&]() {
    auto start = std::chrono::steady_clock::now();
    while (true)
    {
      int i = counter.fetch_sub(1);
      if (i <= 0)
      {
        break;
      }
      DownloadBlobToOptions options;
      options.Range = Azure::Core::Http::HttpRange();
      options.Range.Value().Offset = 0;
      options.Range.Value().Length = 1024 *1024;
     
      std::string blobContent;
      blobContent.resize(1024*1024);
      FillBuffer(&blobContent[0], blobContent.size());
   
      options.TransferOptions.Concurrency = 1;
      std::string blobName = blobNamePrefix + std::to_string(blobSize) + std::string("-") + std::to_string(i);
      
      BlockBlobClient(
      std::string("https://") + accountName + ".blob.core.windows.net/" + containerName + "/"
          + blobName,
      cred,
      clientOptions).DownloadTo(reinterpret_cast<uint8_t*>(&blobContent[0]), 1024*1024, options);
    }
    auto end = std::chrono::steady_clock::now();
    
    ms.fetch_add(std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count());
  };

  std::vector<std::thread> ths;
  for (int i = 0; i < concurrency; ++i)
  {
    ths.emplace_back(threadFunc);
  }

 - OS: Oracle Linux Server release 7.9
 - Version :12-Storage
 - GCC- devtoolset-9

**Comment by vhvb1989** [comment]
What server are you using?

The error you are getting is due to SSL set up:

What is curl error 77 problem with the SSL CA cert?

Curl error 77 error is a server-side error.  This error indicated that the chain certificate files are missing or “broken”. Usually, this error happens simply by outdated SSL certificate(s) for cURL installed on the server.  Also, the wrong or incomplete configuration settings on the server can trigger the error on the website.

https://bobcares.com/blog/curl-error-77-problem-with-the-ssl-ca-cert/

You can try reproducing the issue and setting the SDK logging ON (set env var AZURE_LOG_LEVEL=1 where the test app is running, then run the app and the logs should come the console)
