### ISSUE TITLE
Support for bearer tokens

### ISSUE THREAD

**Issue by janbernloehr** [Azure/azure-sdk-for-cpp#2942]
**Is your feature request related to a problem? Please describe.**
azure-storage-cpplite supported bearer tokens with the `azure::storage_lite::token_credential` class. However, bearer tokens are no longer supported in the azure-sdk-for-cpp out of the box.

This is an issue in many corporate environments where account keys cannot be used since they do no allow for fine-grained access control and also never expire.

**Describe the solution you'd like**
azure-sdk-for-cpp should support token credentials including refresh out of the box.

**Describe alternatives you've considered**
We tried to use SAS tokens but those cannot be created to be valid for multiple containers using azure cli.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by antkmsft** [comment]
Hi @janbernloehr, we do have `Azure::Core::TokenCredential`, but it is an abstract class that gets implemented by different credential types.

I think the closest thing to the bare credential is the `Azure::Identity::ClientSecretCredential` - it does not take the token, but it takes `TeneantId`, `ClientId`, and a `ClientSecret`, and gets the token (and also populates a new one the old one expires).
I think, if your application was using `azure::storage_lite::token_credential`, it did implement fetching that token in some way, was it via client secret?
Here is the sample how to use `ClientSecretCredential`: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/samples/client_secret_credential.cpp

We also have `Azure::Identity::EnvironmentCredential`: it is basically a `ClientSecretCredential`, which reads its input parameters from the environment variables with the argeed-upon names. Because if you use `ClientSecretCredential`, you don't want to hardcode the client secret and you need to read it from somewhere, and the environment is not bad location to read from, in some circumstances, especially if your app runs on an Azure VM, which you can set up to populate the corresponding environment variable during the VM deployment.
Sample: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/samples/environment_credential.cpp

And also, speaking of Azure VMs, `Azure::Identity` also has `ManagedIdentityCredential`, which is supposed to work only when your app runs in Azure, namely on Azure VMs being one of the cases: you enable Managed Identity in the VM properties, and the credential starts working.
Sample: https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/samples/managed_identity_credential.cpp

If you can tell us more how you were using the `azure::storage_lite::token_credential` before, I think we could suggest more specific recommendations. Thank you!

**Comment by Jinming-Hu** [comment]
Hi @janbernloehr , I'm the current maintainer of cpplite sdk. There happens to be another customer who uses a similar way to authenticate requests like you do. I wrote a customized token credential for them and it works great for them. Not sure if it works for you.

```C++
struct SimpleTokenCredential {
  void SetToken(std::string token)
  {
    std::lock_guard<std::mutex> guard(m_mutex);
    m_token = std::move(token);
  }

  std::string GetToken()
  {
    std::lock_guard<std::mutex> guard(m_mutex);
    return m_token;
  }

private:
  std::mutex m_mutex;
  std::string m_token;
};

std::unique_ptr<Azure::Core::Http::Policies::HttpPolicy> MakePolicy(
    std::function<void(Azure::Core::Http::Request&)> func)
{
  class NewPolicy final : public Azure::Core::Http::Policies::HttpPolicy {
  public:
    NewPolicy(std::function<void(Azure::Core::Http::Request&)> func) : m_func(std::move(func)) {}

    ~NewPolicy() override {}

    std::unique_ptr<HttpPolicy> Clone() const override
    {
      return std::make_unique<NewPolicy>(*this);
    }

    std::unique_ptr<Azure::Core::Http::RawResponse> Send(
        Azure::Core::Http::Request& request,
        Azure::Core::Http::Policies::NextHttpPolicy nextPolicy,
        Azure::Core::Context const& context) const override
    {
      m_func(request);
      return nextPolicy.Send(request, context);
    }

  private:
    std::function<void(Azure::Core::Http::Request&)> m_func;
  };

  return std::make_unique<NewPolicy>(std::move(func));
}
```

Use the policy:
```C++
  using namespace Azure::Storage::Blobs;

  std::string accountName = "targettest";
  std::string containerName = "sample-container";
  std::string blobName = "sample-blob";
  std::string blobContent = "Hello Azure!";


  SimpleTokenCredential simpleTokenCredential;
  simpleTokenCredential.SetToken("token1");

  BlobClientOptions clientOptions;
  clientOptions.PerRetryPolicies.emplace_back(
      MakePolicy([&simpleTokenCredential](Azure::Core::Http::Request& request) {
        request.SetHeader("Authorization", "Bearer " + simpleTokenCredential.GetToken());
      }));
  auto containerClient = BlobContainerClient::BlobContainerClient(
      https:// + accountName + ".blob.core.windows.net/" + containerName, clientOptions);

  containerClient.CreateIfNotExists();

  BlockBlobClient blobClient = containerClient.GetBlockBlobClient(blobName);

  // Let's say token expired and we want to refresh it.
  simpleTokenCredential.SetToken("token2");  // Token is protected by mutex, so this function can be called synchronously or asynchronously.

  std::vector<uint8_t> buffer(blobContent.begin(), blobContent.end());
  blobClient.UploadFrom(buffer.data(), buffer.size());

  Azure::Storage::Metadata blobMetadata = {{"key1", "value1"}, {"key2", "value2"}};
  blobClient.SetMetadata(blobMetadata);

  auto properties = blobClient.GetProperties().Value;
```

**Comment by janbernloehr** [comment]
Thanks for the extensive example. If I understand it correctly, it does not feature auto-renew of tokens, though? This would be the most important missing piece.

**Comment by Jinming-Hu** [comment]
> If I understand it correctly, it does not feature auto-renew of tokens, though?

Nope. It provides the same functionality as cpplite. I don't know if that can help your migration from cpplite to this SDK.

**Comment by antkmsft** [comment]
@janbernloehr, I think we've provided a solution for the storage_lite token credential, with the code above. We are not currently planning to have it as part of the SDK, because token refresh is problematic. There are similar in spirit types of credentials, such as AzureCli credential which I think we can implement.

Other recommendation is also to update your app to use currently available and supported credentials.

I am closing this issue - please reopen it if you think we should reconsifer storage_lie token credential, or contact us if you have more questions.
If you need Azure CLI credential, please open another issue, and we will look into it.

**Comment by antkmsft** [comment]
@janbernloehr, we just added Azure CLI Credential to `main` (#4146). It does invoke `az account get-access-token` and uses that token. It also handles token expiration, and requests a new token if the old one is about to expire or has expired. If you have any feedback, please let us know!
