### ISSUE TITLE
Vcpkg comment tag failed

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3061]
The VCPKG comment tag failed.
+ $prOwners = D:\a\_work\1\s/eng/common/scripts/get-codeowners.ps1 ` 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : ObjectNotFound: (D:\a\_work\1\s/eng/…/get-codeowners.ps1:String) [], ParentContainsErrorRecordException

**Comment by danieljurek** [comment]
`get-codeowners.ps1` has been removed. 

Change: https://github.com/Azure/azure-sdk-for-cpp/commit/24b34875ff22fa0d5d060066db0efe85bba7c4a7

Failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1179876&view=logs&j=6d63b2a5-a608-50ae-6bee-c0a1cf664e1f&t=063b5c9b-1ec2-58d9-0ee8-2771d0581a79

Looks like the way to go forward is to use `identity-resolver` or `/eng/common/pipelines/templates/steps/get-pr-owners.yml`

**Comment by kurtzeborn** [comment]
This was initially blocked because of the lost script @weshaggard mentioned above.  That script has been restored, so this is unblocked.  @sima-zhu is also working on improvements and consolidation related to what this script does, so it will be important that she validate this scenario is not broken when she is completing that work.

**Comment by weshaggard** [comment]
This should be fully fixed now with https://github.com/Azure/azure-sdk-for-cpp/pull/3130
