### ISSUE TITLE
Clean up EngSys branches

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#3116]
https://github.com/Azure/azure-sdk-for-cpp/branches/all

Some branches look like they are personal branches, some are stale. Almost all belong to EngSys, so I suggest to assign this work item to them.

I think there should not be personal or engsys branches at this point, that are only made for the purposes of making a PR. Instead, you fork the repo, create the branch there, and create a PR to this repo - just as we do with our dev branches.

If it is a feature, or another branch of this sort, intended for long life, it is ok.

**Comment by RickWinter** [comment]
@danieljurek Can this be prioritized so we can close out this issue

**Comment by danieljurek** [comment]
A lot of EngSys work needs to happen in branches off the main repo instead of in a fork. In almost every case where I create a branch from a fork I end up moving it into the main repo to test some scenario or another. 

djurek/* branches deleted, following up on the others...

**Comment by danieljurek** [comment]
Following up on remaining branches: 
@chidozieononiwu -- Can you have a look at these branches and delete them if they're no longer needed: 
* UpdateUbuntuVMImage ([compare](https://github.com/Azure/azure-sdk-for-cpp/compare/UpdateUbuntuVMImage?expand=1)) -- We're specific about the VM images we're using here so I think updating this is not the right move... this branch can also be deleted because the work of setting image versions is [happening here](https://github.com/Azure/azure-sdk-for-cpp/pull/3553)
* MarkTemplateAsTestPkg ([compare](https://github.com/Azure/azure-sdk-for-cpp/compare/MarkTemplateAsTestPkg?expand=1))
* PrepForToolsChanges ([compare](https://github.com/Azure/azure-sdk-for-cpp/compare/PrepForToolsChanges?expand=1))

**Comment by danieljurek** [comment]
@sima-zhu  -- Can you look at this branch and delete if it's no longer needed: 
* gh-pages-root ([compare](https://github.com/Azure/azure-sdk-for-cpp/compare/gh-pages-root?expand=1))

**Comment by sima-zhu** [comment]
> @sima-zhu -- Can you look at this branch and delete if it's no longer needed:
> 
> * gh-pages-root ([compare](https://github.com/Azure/azure-sdk-for-cpp/compare/gh-pages-root?expand=1))

No. It is still in use in docindex. [link](https://github.com/Azure/azure-sdk-tools/blame/main/eng/common/pipelines/templates/jobs/docindex.yml#L50)

gh-pages is a one commit branch. So we need to start from an empty repo every time we push the changes. That's the reason we have to retain the gh-pages-root.

**Comment by danieljurek** [comment]
@sima-zhu -- Looks like we should put a branch protection rule in place.

**Comment by sima-zhu** [comment]
> @sima-zhu -- Looks like we should put a branch protection rule in place.

That's great idea. I don't have permission to do so. @danieljurek Could you help setup the protection rule?

**Comment by danieljurek** [comment]
@chidozieononiwu -- Would you have a look at the branches and let us know if we need to keep those around? https://github.com/Azure/azure-sdk-for-cpp/issues/3116#issuecomment-1108856971

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu -- Would you have a look at the branches and let us know if we need to keep those around? [#3116 (comment)](https://github.com/Azure/azure-sdk-for-cpp/issues/3116#issuecomment-1108856971)

I have removed them all.

**Comment by danieljurek** [comment]
Thanks everyone. There are a few remaining eng/common branches for ongoing work and those will be cleaned up as that work merges. 

We can close this one now :)
