### ISSUE TITLE
By default, when building, use less strict warning level

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#3172]
When customer builds us, and also when we are built via vcpkg, we should not treat warnings as errors, as well as warning level should be lower (1? 2? 3? 0?). So that, things like unknown doxygen tags do not fail the build, and also when we are build with the compiler/version that we don't run in our CI.
And in our CI, and maybe when we as devs build locally, let's still compile with the highest warning level.
We do have `WARNINGS_AS_ERRORS` build option, maybe it is sufficient, maybe we also need to add something like `STRICT` option which is off by default (but is ON in our CI), and if it is off, it drops the warning level to less than the default.
Maybe we can even disable warnings all together, because we still do check warnings when developing/running in our CI.

**Comment by ahsonkhan** [comment]
Would it be sufficient to just simply turn `WARNINGS_AS_ERRORS` off for when our customers build our SDK? We expect 0 warnings anyway (given our CI/CD will continue to treat warnings as errors), and in the small chance that customers using newer compilers hit new warnings, they can report issues that can help us address them, rather than silently removing them all together.
