### ISSUE TITLE
It is very unclear what the library does when it verifyHost 

### ISSUE THREAD

**Issue by edwardt** [Azure/azure-sdk-for-cpp#3204]
**Query/Question**
A clear and concise ask/query.
 When set to verify host, there are multiple options that openssl does to verifyhost.
The library uses curl underneath= https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html
There is only a few basica sentence in the doc
https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.0.0-beta.8/struct_azure_1_1_core_1_1_http_1_1_curl_transport_ssl_options.html

But does not say much what the checks are. There are others options as listed below (e.g. CURLSSLOPT_NO_PARTIALCHAIN) 
https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html
I can't tell if the check in the liobrary is using CURLSSLOPT_NO_PARTIALCHAIN or it is doing more, when verifyHost is set.

If it is not set how can I set it for verifyHost?
***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by edwardt** [comment]
IT does not look like It does not look like the library enables ssl tls hostname validation for options like wildcard hostname matching?

location:
azure-sdk-for-cpp/sdk/core/azure-core/src/http/curl/curl.cpp:1381
openssl flag:
https://www.openssl.org/docs/man1.1.1/man3/X509_VERIFY_PARAM_set1_host.html for example:
X509_V_FLAG_PARTIAL_CHAIN 

Is it possible for end user to configure setting such as X509_V_FLAG_PARTIAL_CHAIN  themselves?

**Comment by vhvb1989** [comment]
Hey @edwardt, thank you for reaching out.

It looks like libcurl uses `CURLSSLOPT_NO_PARTIALCHAIN` to set `X509_V_FLAG_PARTIAL_CHAIN`.  ([see this](https://github.com/curl/curl/issues/5374) and [this](https://stackoverflow.com/questions/59095247/curl-easy-option-for-x509-v-flag-partial-chain)). 

What libcurl version are you using?  It should be the default behavior since version 7.68.0. ( Have you tried using this version or greater? )

The Azure SDK for C++ requires libcurl MIN Version 7.44;  which means that from 7.44 to 7.68, the option wouldn't be available.

I noticed you shared a link from the Azure SDK docs that points to an old beta release. Please use a more recent GA version like : [1.3.1 release docs](https://azuresdkdocs.blob.core.windows.net/$web/cpp/azure-core/1.3.1/struct_azure_1_1_core_1_1_http_1_1_curl_transport_options.html)

The Azure SDK provides only a few settings for libcurl's handle customization ( not all settings are there ).  I have been adding each setting upon customer's requests. Just like you noticed, for the [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html), we currently only support the setting `CURLSSLOPT_NO_REVOKE` ( using the name `EnableCertificateRevocationListCheck` ), which is only for schannel on Windows, so it has no impact when using OpenSSL.

Have you tried using the option [CURLOPT_SSL_VERIFYPEER](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html) ?  You can set it `false` directly from the `CurlTransportOptions`.

Please let me know if you have any other question. I'd be happy to help

**Comment by vhvb1989** [comment]
>When set to verify host, there are multiple options that openssl does to verifyhost.
The library uses curl underneath= https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html

The Azure SDK for C++ doesn't change or expose the `CURLOPT_SSL_VERIFYHOST` option (so it uses libcurl default). Customer can update the option  `CURLOPT_SSL_VERIFYPEER` from its default. 

> I can't tell if the check in the liobrary is using CURLSSLOPT_NO_PARTIALCHAIN or it is doing more, when verifyHost is set.

Can you elaborate on what setting you are referring from the SDK as the `verifyHost` ?  
`CURLSSLOPT_NO_PARTIALCHAIN` is never updated from its default value.

**Comment by edwardt** [comment]
I was asking what does AZURE SDK CPP do for tls hostname validation. I think you already answered mny quetion being that it uses curl defaults and not letting end user to change it from AZURE side, if any change of options required it has to be done on the curl side.

**Comment by vhvb1989** [comment]
> and not letting end user to change it from AZURE side

The Azure SDK lets you set/change a few libcurl settings using the `libcurlTransportAdapterOptions`.  Each option is mapped to one of libcurl's options.

If you want to take full control of the libcurl handle, you can also create a transport adapter.  See an example [here](https://github.com/vhvb1989/libcurl-callbacks-transport-adapter)

Let me know if you have more questions or if anything else I can help
