### ISSUE TITLE
BaseStream.Length() shouldn't need to be necessary prior to BlockBlobStorageClient.Upload

### ISSUE THREAD

**Issue by ashf** [Azure/azure-sdk-for-cpp#3207]
**Is your feature request related to a problem? Please describe.**
I created my own BaseStream implementation with the OnRead function mimicing libcurl's readdata callback function. However, due to the work that is being done in that function (librsync delta creation via it's streaming api) I don't know the size of the uploaded data before calling BlockBlobStorageClient.Upload. Ideally, the length of the stream shouldn't need to be known before the upload.

**Describe the solution you'd like**
Uploading via libcurl doesn't require the size to be known ahead of time, so I'd think the azure library shouldn't either.

**Describe alternatives you've considered**
Only alternative I can think of is to do a block stage and commit (where the block size is small enough that it's not too much data in memory at one time)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Jinming-Hu** [comment]
Hi @ashf , if you look at the REST API reference, the `Content-Length` header is sent before sending out the HTTP request body. So I think the length is required to be known before uploading.

> Uploading via libcurl doesn't require the size to be known ahead of time

Do you know how it's implemented in libcurl? Does libcurl cache all the data in memory and only start uploading when it gets all the data and knows the length? If that's the case, we cannot do that, because many of our customers transfer huge size of data to/from storage that memory is not big enough to cache all the data.

> Only alternative I can think of is to do a block stage and commit (where the block size is small enough that it's not too much data in memory at one time)

I believe this is the right way to go.

**Comment by ashf** [comment]
> Do you know how it's implemented in libcurl? Does libcurl cache all the data in memory and only start uploading when it gets all the data and knows the length? If that's the case, we cannot do that, because many of our customers transfer huge size of data to/from storage that memory is not big enough to cache all the data.

Unsure of how libcurl does it under the hood. I think it has more to do with how the receiving endpoint handles an unknown content length (but I could be mistaken).

I have switched to using the block stage/commit and that works well for my needs. Thanks.
