### ISSUE TITLE
Decrease reaction time to discover failures within the daily vcpkg PR, to fix issues before the release, by notifying the team

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3242]
Is there a mechanism with which the team can be notified via email whenever https://github.com/microsoft/vcpkg/pull/17119 fails to pass CI?

Making it a push mechanism rather than having someone poll the PR regularly, specifically on an error, would be quite helpful. Hopefully, it isn't too noisy though :)

I believe the vcpkg repo notifies the author of the PR, so maybe this is as simple as setting up an email forwarding rule to route to the right folks from the azure-sdk GitHub account.

If not, any other ideas, so that we don't end up discovering issues or build failures on the day of/week of the release, but rather closer to when a potential issue gets introduced?

cc @vhvb1989

**Comment by kurtzeborn** [comment]
Because of the uniqueness of how we "release" in CPP, this may be difficult.  The pipeline creates the pull request and if that fails, it will automatically notify anyone listed in CODEOWNERS.txt if that fails.  If the PR is invalid, there's no notification system for that because the pipeline has already exited at that point.

You could do this with a GitHub bot, but since we don't own the repo these PRs are being created in, we couldn't even add a bot for that.
