### ISSUE TITLE
Blob upload/download perf tests fail when size=1GB and parallel=8

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-cpp#3424]
A primary blob perf test is to upload/download 1GB blobs with parallel=8.  This works in .NET, Java, JS, and Python because they upload/download from/to streams, which can be implemented to simulate 1GB of data without allocating 1GB of memory.

However, these tests currently fail in C++, since the tests upload/download from/to vectors, which requires allocating 1GB of memory per upload/download, which causes the test to fail on our perf VMs (4 cores, 14GB memory).  I suspect the test is running out of memory.

**Comment by vhvb1989** [comment]
There are 2 Download API versions for the blob client in C++:

- Download()

This operation returns a model containing a `bodyStream` which can be used to pull data to be downloaded.
This operation supports `parallel=1` only. Only one thread should read from the `bodyStream` at a time.
The `bodyStream` is an Azure Core model which represents a `Read Only` Stream type.
This operation allow customers to re-use one buffer to download a big blob, but the download is done from one connection only.

- DownloadTo()

This operation must take either a file or a contiguous buffer where to download the blob content.
The operation supports parallelism. 
The number of threads to use is set by the operation options (input parameter).
Each thread uses one connection to the server and downloads a chunk of the entire blob content into either a file or a buffer.
The address of where each thread writes the downloaded bytes is calculated based on the chuck of data downloaded. For a 100 bytes blob, using 10 threads with chuck size equals to 10 would create 10 connections where each connection would download 1/10 of the response each. First connection will write the first 10 bytes, second connection will write the next 10 bytes, and so on. 

Each thread uses the `Download() ` operation, but it does not support downloading content into temporal buffers. Mainly because the address for where to write the content is calculated by the API and needs to be found within the file or buffer.

## Conclusion

C++ does not support downloading a blob using multiple threads and making each thread to download and discard the blob content.

**Comment by mikeharder** [comment]
I think the best we can do here is add perf tests in C++ for all three scenarios:

1. Call `Download()`, read the `bodyStream`, and discard the bytes as they are read.  Should not require much memory in client process, but the download can only use a single HTTP connection.

2. Call `DownloadTo()` with buffers.  Does not depend on the disk and supports multiple HTTP connections, but limits client parallelism due to large memory requirements.

3. Call `DownloadTo()` with files.  Supports multiple HTTP connections and should not require much memory, but may be throttled by disk performance.

Unfortunately none of these are directly comparable to the other languages, which support downloading with multiple HTTP connections to a client `stream` that can be simulated with very little memory.

**Comment by gearama** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1934584&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056
