### ISSUE TITLE
There's no way to skip proxy for a specific request disregarding proxy environment variable

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3537]
The doc for `CurlTransportOptions::Proxy` says 

> @remark The default value is an empty string (no proxy).

which is inaccurate according to CURL API reference https://curl.se/libcurl/c/CURLOPT_PROXY.html.

> Setting the proxy string to "" (an empty string) will explicitly disable the use of a proxy, even if there is an environment variable set for it.
> The [CURLOPT_PROXY](https://curl.se/libcurl/c/CURLOPT_PROXY.html) and [CURLOPT_NOPROXY](https://curl.se/libcurl/c/CURLOPT_NOPROXY.html) options override environment variables.

There are two scenarios with a small difference here:
1. proxy is not set, follow environment variable.
2. proxy is explicitly set to empty, do NOT use proxy even if environment variable is set.

With current curl transport implementation, we can only do 1) but not 2).

I encountered this problem when I'm working on a small project recenlty, where user can use a global proxy for all programs by setting environment variables.

But the program itself will send out some requests to localhost, which shouldn't go through proxy. An example of such requests is [Access Azure Instance Metadata Service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=linux#access-azure-instance-metadata-service).

Is there any way to get around this issue? @vhvb1989

**Comment by vhvb1989** [comment]
> Is there any way to get around this issue? @vhvb1989

How are you consuming/integrating the SDK to your application?  Your options will be around that. For example:

- If your app is using cmake and fetch-content to get the Azure SDK, then you can create a fork and make fetch-content to get your fork. Then, in your fork you can decide how to handle the proxy option. You can change the option to be a Nullable<T>, or you can add a new option `override proxy` to force using any value in the proxy options, even if it is empty string.
- If you are Using windows, you can switch to winHTTP for those requests with no proxy (IIRC, the winHTTP does not honor the proxy env var)
- If the requests are not happening at the same time (like multi-thread), you can explore the option of changing the env vars for proxy before your request and restoring after. ( an ugly solution)
- If you are using VCPKG to consume the SDK, it will be more problematic, as you will need to user overlay ports to ask VCPKG to fetch the package from a different location that you will set (I can give you more info if you want to explore this)
- If you don't want to change the SDK code, you can also copy/paste all the libcurlTransportAdapter code to your application and create your own transportAdapter for your application.  You can then make any changes you need to it on your application side and just use it to init the SDK client.
- If you won't call the `download()/downloadTo()` api, you can also consider this transport adapter: https://github.com/vhvb1989/libcurl-callbacks-transport-adapter .  It can't be use for `download` because it doesn't support streaming data from network (it uses a temporal buffer just like track 1), so a big download would fail.

I think those are your `fast options`.  On the long term, I will talk to the Azure Core team to see how we want to handle this.  As changing the option to a Nullable<T> is a breaking change, maybe we would just add the `no-proxy` option and mention that it overrides the proxy option and the env vars configuration.  I would expect Azure Core to support this by `May Release`

**Comment by Jinming-Hu** [comment]
> On the long term, I will talk to the Azure Core team to see how we want to handle this. As changing the option to a Nullable<T> is a breaking change, maybe we would just add the no-proxy option and mention that it overrides the proxy option and the env vars configuration.

That's not ideal. What if customers set both `no-proxy` option and `proxy` option. That's ambiguous.

One way I can think of is to define a constant string, the value of which is not a valid proxy, like `const std::string ForceNoProxy = "(NO_PROXY)";`. If this value is set, we'll call `SetLibcurlOption(CURLOPT_PROXY)` with an empty string.
