### ISSUE TITLE
[Technical Question] : Append live file content to blob and get event for each append operation on Azure cloud.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-sdk-for-cpp#3573]
**Query/Question**

How to Append data to azure blob and get event for each appended operation on Azure cloud.

Our use case is as follows.

1. Upload a local-file(present on device) which is open in append mode and data in this file are getting appended continuously  .
2.  Append only newly added content from local-file to azure blob. 
3. Get event for newly added data at azure blob storage. we expect to get event for newly-appended-data(delta) to azure blob.

**Setup :**
 - OS: Linux (Ubuntu).
 
So far I tried this with running local-blob-storage module on iotedge and doing Append block. I can see the Append block operation is appending data to local blob as well synching with azure blob storage at cloud. But i don't get change event for the appended data. 

I need a change event for each appended block.

Can we achieve this using put blob instead of append blob ?

OR
Could you please suggest the correct way to implement this use case.

**Comment by sanjeev-magoo** [comment]
/unresolve
We are looking for events whenever a blob is sync by IoTEdge to Azure blob storage in Azure cloud. We are following https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2020-11 documentation.

Our current solution -

Local live updating file --->custom module (appending data from local live updating file to local blob storage running on IoT Edge)------->IoTEdge is synching local blob (IoTEdge is having details of remote blob storage) ----->to remote Blob storage on Azure cloud----->Custom service (Needs event whenever a blob is getting appended)-----> Read blob and perform business processing.

In other words, we have a custom module in IoTEdge which is reading a local live updating file and appending the content to local blob storage running on IoTEdge. We have configured IoTEdge to automatically sync blob from local blob storage to Azure blob storage on cloud. Note- This is working fine and IoTEdge is syncing local blob file with blob at azure cloud. Now, we want whenever blob at azure cloud is getting appended, we need an event so that we can perform some business operation.

1. With Append blob type, we are not getting events for appended operation. Can you please let us know if we can get appended blob event from Azure blob storage in cloud? 
2. How can we append a file using block blob? It will be great if you can refer some example on the same.
3. can we get appended blob event using block blob in Azure cloud?

**Comment by rajaggrawal** [comment]
/unresolve
We are looking for events whenever a blob is sync by IoTEdge to Azure blob storage in Azure cloud. We are following https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2020-11 documentation.

Our current solution -

Local live updating file --->custom module (appending data from local live updating file to local blob storage running on IoT Edge)------->IoTEdge is synching local blob (IoTEdge is having details of remote blob storage) ----->to remote Blob storage on Azure cloud----->Custom service (Needs event whenever a blob is getting appended)-----> Read blob and perform business processing.

In other words, we have a custom module in IoTEdge which is reading a local live updating file and appending the content to local blob storage running on IoTEdge. We have configured IoTEdge to automatically sync blob from local blob storage to Azure blob storage on cloud. Note- This is working fine and IoTEdge is syncing local blob file with blob at azure cloud. Now, we want whenever blob at azure cloud is getting appended, we need an event so that we can perform some business operation.

With Append blob type, we are not getting events for appended operation. Can you please let us know if we can get appended blob event from Azure blob storage in cloud?
How can we append a file using block blob? It will be great if you can refer some example on the same.
can we get appended blob event using block blob in Azure cloud?

**Comment by Jinming-Hu** [comment]
Getting events for blob changes is out of storage client's scope.

> How can we append a file using block blob? 

You can call [GetBlockList](https://github.com/Azure/azure-sdk-for-cpp/blob/7b87ea1c85357c7cea6303147b21fc15a3d9bd0b/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/block_blob_client.hpp#L240), [StageBlock](https://github.com/Azure/azure-sdk-for-cpp/blob/7b87ea1c85357c7cea6303147b21fc15a3d9bd0b/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/block_blob_client.hpp#L184), then [CommitBlockList](https://github.com/Azure/azure-sdk-for-cpp/blob/7b87ea1c85357c7cea6303147b21fc15a3d9bd0b/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/block_blob_client.hpp#L224).

**Comment by sanjeev-magoo** [comment]
@Jinming-Hu - Thanks for quick response.

[Getting events for blob changes is out of storage client's scope.]- Not sure if I fully get this, as I am **not** talking about storage client here. I am asking for event from Azure blob storage, whenever a blob is appended, Azure blob storage should be able to emit event similar to events mentioned at below link.
https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=event-grid-event-schema

I believe, this should be fall under responsibility of Azure blob storage to emit such event whenever a blob is appended. Can you please take this with product team ?

It will be great if you can point to some sample program for append operation using block blob or let us know the SDK function supporting appending a blob using block blob type.

**Comment by Jinming-Hu** [comment]
I don't know about Azure Event Grid. Maybe you should open a support ticket on Azure Portal.
