### ISSUE TITLE
As a contributor, how do I build the SDK as release rather than debug via the command line?

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3600]
Is the recommended pattern to specify as a cmake option?

Is passing `-DCMAKE_BUILD_TYPE=Release` to cmake sufficient here?

If so, we should consider adding that build option to:
https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#cmake-build-options

In VS `CMakeSettings.json`, we have the `"configurationType": "MinSizeRel"` configuration to distinguish between debug and release.
https://github.com/Azure/azure-sdk-for-cpp/blob/5cb60868e158ed54b9d0a1d732f225e4c38ce916/CMakeSettings.json#L60

cc @vhvb1989

**Comment by vhvb1989** [comment]
When working with CMake, there are 2 types of generators, the `multi-config generators` [see more](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) and the `single-config generators`.

For `single-config generators`, the build type is defined by an option when the project is generated (when you call `cmake -DFOO=BAR .`  You don't need to set the `--config Release` option when building a `single-config project`, as the build_type is defined when the project is generated.  Then, calling `cmake --build .` will just produce the binaries based on `DCMAKE_BUILD_TYPE`.  
make and ninja are single config.  You can't build multiple binaries (rel, debug, etc.) from the same project if it is single-config.
You would need to clean and re-generate the project whenever a different release mode is desired.
We use this mode for all Linux CI gates (with make generator).

For `multi-config generator`, the generated project is not related to a particular build mode. The `DCMAKE_BUILD_TYPE` option in this case is ignored by CMake.
The build type is, instead, defined on build time (when you call `cmake --build`) by using `--config <mode>`.
multi-config projects can build different binaries from the same project. They usually add a folder before the binary to mention the build mode (debug, Release, etc).
VSProject. Xcode and Ninja-multi are these type.
We use this mode for Windows CI gates (the generator is a Visual Studio project).

This information has no relation to Azure SDK in particular. It is CMake domain specific.  I don't think we should document this within the Azure SDK docs because it belongs to CMake.  

We should be fine as long as we mention the generator type we are using for each script we document in the readMe files
