### ISSUE TITLE
Authentication authority URL is missing for ManagedIdentityCredential class

### ISSUE THREAD

**Issue by cyrus-jackson** [Azure/azure-sdk-for-cpp#3638]
**Describe the bug**
`authorityHost` is missing in `ManagedIdentityCredential` class.  `authorityHost` is present in `ClientSecretCredential` class. I can also see the equivalent in Java sdk. Is there any specific reason why this was not included?

**Comment by antkmsft** [comment]
@cyrus-jackson, `ManagedIdenttyCredential` endpoints are read from the environment variables such as `MSI_ENDPOINT`, `IDENTITY_ENDPOINT`, and `IMDS_ENDPOINT`. Having `AuthorityHost` property in `TokenCredentialOptions`, or making `ManagedIdentityCredentialOptions` and adding that property there, would have no effect on the endpoints that `ManagedIdenttyCredential` would try to reach to authenticate.
I think it is likely that Java SDK has that property in `IdentityCredentialOptions`, because good portion of credentials would use it. But `ManagedIdentityCredential` won't.

**Comment by antkmsft** [comment]
@cyrus-jackson, please reopen this issue if you have more questions or think there are other things to consider.
