### ISSUE TITLE
Can we increase receive timeout for WinHTTP transport?

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3642]
The default receive timeout for WinHTTP connections is 30 seconds. Storage service usually takes longer than that to respond to Query requests. As a result, client usually needs to retry 3 or 4 times to get a response within 30 seconds. This wastes quite some time and bandwidth.

So we'd like to see if we can increase the timeout to a larger value, or expose this as an option so that client can customize as needed.

As a reference, libcurl doesn't timeout once the connection is established.

REF:
https://docs.microsoft.com/en-us/windows/win32/api/winhttp/nf-winhttp-winhttpsettimeouts
https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html

**Comment by ahsonkhan** [comment]
@Jinming-Hu, what would you see the timeout option too, specifically for query APIs, given 30 seconds is too short? Does the service has a guaranteed upper bound for how long it will take to respond?

**Comment by ahsonkhan** [comment]
There's also a difference in the default connection timeouts between the curl transport adapter (we set to 5 min) and winhttp (set to 1 min).

**Comment by Jinming-Hu** [comment]
@ahsonkhan I didn't find SLA about response time. I think 3 minutes is a reasonable time. It's not too long, and it's long enough for Query.

Connection timeout doesn't break storage at the moment, so I'm fine to leave it as is.

**Comment by Jinming-Hu** [comment]
I found [this](https://azure.microsoft.com/en-us/support/legal/sla/storage/v1_5/) link. We don't have SLA for Query API yet.

**Comment by XiaoningLiu** [comment]
Bump up this ask from Azure Storage service team. We are exploring to consume Azure Storage CPP SDK inside backend service. However, there is a requirement to fine grained control HTTP timeouts settings. For example, 4 kinds of timeout settings to be consumed by upper layer.

       ::WinHttpSetTimeouts(
            requestHandle,
            timeoutInMs /* dwResolveTimeout */,
            timeoutInMs /* dwConnectTimeout */,
            timeoutInMs /* dwSendTimeout */,
            timeoutInMs /* dwReceiveTimeout */);

**Comment by Jinming-Hu** [comment]
@RickWinter @ahsonkhan Can you prioritize this feature request? We have different cases that require customizable timeouts for transport layers.

**Comment by LarryOsterman** [comment]
It's possible that [this](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags#winhttp_option_receive_response_timeout) can increase the receive response timeout.

[this](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags#winhttp_option_connect_timeout) can be used to increase the connect timeout.
[this](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags#winhttp_option_resolve_timeout) can be used to increase the DNS resolution timeout.
and finally [this](https://learn.microsoft.com/en-us/windows/win32/winhttp/option-flags#winhttp_option_send_timeout) can be used to set the send timeout.

We can expose all 4 of these timeouts in seconds in the WinHTTP client options which storage can then use if it needs to modify the WinHTTP options.

Exposing WInHttpSetTimeouts seems like a poor choice since it forces all the values to be set explicitly.
