### ISSUE TITLE
If we need OpenSSL >= 3.0.2, say so instead of 1.1.1n

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#3703]
"[W]e're at OpenSSL 3.0.2, I believe, not 1.1.1n."

_Originally posted by @LarryOsterman in https://github.com/Azure/azure-sdk-for-cpp/pull/3701#discussion_r888611927_

**Comment by antkmsft** [comment]
@LarryOsterman Would you mind to check if we do require min version of 3.0.2, and update all occurrences of `"1.1.1n"` (there might be more than in this PR), or in general if there is ever a dependency on `openssl` without min version specification, also put it there?

**Comment by LarryOsterman** [comment]
We shouldn't have *any* version dependencies in packages unless we have a strict requirement that a package be greater than a particular value. Otherwise we should let the vcpkg base line determine the package.

For instance, we *require* OpenTelemetry 1.3.0 (because we require a bug fix which is only available in OpenTelemetry 1.3.0). But we don't have such a requirement for OpenSSL, just that we have the most recent version in teh vcpkg baseline.

**Comment by antkmsft** [comment]
So, should we drop all `"version>="` for OpenSSL then?
I think you added the `"version>="`, and you're the biggest OpenSSL user, can you remove it?

**Comment by LarryOsterman** [comment]
I have the fix ready for my next PR
