### ISSUE TITLE
Make sure to call Url Encode on user input where needed, in cases like KeyVault

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#3883]
The user-input data here is not being encoded.
https://github.com/Azure/azure-sdk-for-cpp/blob/c152c05d4a56074d20451b7efa483bbf17bef116/sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp#L478-L479

We should audit other places that might have this issue.

For example, in golang, they are encoded:
https://github.com/Azure/azure-sdk-for-go/blob/37f3c8dd2e9bafb7b6bf9aabb0795e753038928d/sdk/keyvault/azkeys/client.go#L276-L277

**Comment by ahsonkhan** [comment]
cc @gearama, @vhvb1989, @LarryOsterman

**Comment by vhvb1989** [comment]
we don't need to encode `_detail::KeysPath` because it is only letters (ALPHA) 
![image](https://user-images.githubusercontent.com/24213737/184246804-cfae19f4-f079-413d-be3d-5109de0318c1.png)

We don't need to encode the `name` because the keyvault names can only be created with letters, numbers and dashes:
See help info from creating a key from Azure Portal:
![image](https://user-images.githubusercontent.com/24213737/184247051-87e7f35d-fa5f-4d99-99ae-97288babbc95.png)

So there's never a case where we will have a name with characters that requires encoding.

**Comment by vhvb1989** [comment]
> in golang, they are encoded:

If golang is auto-gen, it makes sense...  The result string will always going to be the same.

For non-generated code, we know about the single case.

I would just add comments in the code about why we are not encoding there.  And I wouldn't expect that auto-gen to know when to use Encode() and when not to.  I would expect autoget to always call `Encode()` for addPath and for addQuery (just making sure it is called only once to avoid re-encoding)

**Comment by ahsonkhan** [comment]
What about version? Is that documented/guaranteed to always be something like a Guid?
https://github.com/Azure/azure-sdk-for-cpp/blob/c152c05d4a56074d20451b7efa483bbf17bef116/sdk/keyvault/azure-security-keyvault-keys/src/key_client.cpp#L482

**Comment by vhvb1989** [comment]
The version comes from the API spec directly:
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/data-plane

https://github.com/Azure/azure-rest-api-specs/tree/main/specification/keyvault/data-plane/Microsoft.KeyVault/stable

It looks like we use semVer, and if that's correct, we won't need to encode it (at least for Key Vault)

I would check with Arch board or PMs if the Azure SDK has any guidelines for the version string used on data-plane sdk
