### ISSUE TITLE
PLEASE add timestamp and session-id into logging policy 

### ISSUE THREAD

**Issue by yxiang92128** [Azure/azure-sdk-for-cpp#3943]
**Is your feature request related to a problem? Please describe.**
In the legacy SDK, via boost logger, I can get detailed log entry with timestamp and session id such as the following:
**2022-07-28 15:53:14 0433481E-1E0E-460C-8AA3-855F363E4C6D** : Retry policy did not allow for a retry, so throwing exception: The account being accessed does not support http.

but in track2, after SetListener, the message captured in the listener only has the error message itself, for instance,
HTTP Transport error: Fail to get a new connection for: ://. URL using bad/illegal format or missing URL

there is NO timestamp and there is NO unique session id which could help in debugging multiple interleaved requests.
**Describe the solution you'd like**
 add support for timestamp and session-id in built-in log policy. Or add an additional user input field in the SetListener callback so the caller can pass in additional info to track where the log comes from.

**Describe alternatives you've considered**
N/A
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yxiang92128** [comment]
@RickWinter 
Is there a way you can provide an estimate when this will be implemented?  We are looking to productize this SDK in Q4 thus logging is a crucial component for us.
Thanks,

Yang

**Comment by yxiang92128** [comment]
At what time do you want to print logs, before the request is sent over the wire or after receiving a response, or both
Both
What kind of information do you expect to be included in logs? Like request url, headers, status code, etc.
In trace (verbose) mode, we need timestamp, session id, url, headers and status/error string to be dumped to the log.  In warn or error mode, time stamp, url, status and error messages should be dumped.
Is there any other non-HTTP-specific information you’d like to include in logs except timestamp and session-id you’ve mentioned in the GitHub issue?
Perhaps from track2 SDK level, say operation completed or failed in verbose mode and also any error messages generated from the SDK in error/warn mode?

**Comment by antkmsft** [comment]
You can add a timestamp in your implementation of a log listener. For example, see how EnvironmentLogLevelListener does append a timestamp and a thread id: https://github.com/Azure/azure-sdk-for-cpp/blob/ccddc7f3ed7f0c71ad99a2d01398fcd3aa6596d7/sdk/core/azure-core/src/environment_log_level_listener.cpp#L121-L145

1. You could produce the timestamp the same way.
2. I do not know what a session ID is - I don't think this SDK has this concept, at least not at an SDK level.
3. That implementation could either append the timestamp to the message, or, if you are, for example, exporting to a database, could put it into a separate field.

Just for infornation, it is possible that EnvironmentLogLevelListener could work for you to some extent?
If you set an `AZURE_LOG_LEVEL` environment variable (https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core#sdk-log-messages), then you could redirect standard error to the log file, and it will have timestamps (because EnvironmentLogLevelListener adds them)
```
myprogram.exe 2> log.txt
```
