### ISSUE TITLE
Split test capture step out from build step

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3951]
Currently the builds run gtest_discover_tests as a final step of the tests.  This step should be split out into its own step to speed up the builds and help isolate points of failure.

**Comment by ahsonkhan** [comment]
Related issue tracking resolving the failures:
https://github.com/Azure/azure-sdk-for-cpp/issues/1607

**Comment by gearama** [comment]
Having isolated the point of failure to GTest_Discover_Tests , splitting the step out is pointless and actually lengthens the build process as it being part of the cmake files, the only way to have it executed or not is to run cmake config / build twice. which overall lengthen the build process. 
We cannot have only the discovery test step run , but we can actually increase the timeout of the discovery from 5 s currently ( which is too short ) to something more apropriate. 
To quote the cmake gtest documentation for discovery timeout "Most test executables will enumerate their tests very quickly, but under some exceptional circumstances, a test may require a longer timeout. The default is 5. " the exceptional circumstances are not elaborated further. 
Why the current implementation of the timeout is not working is due to the fact that it is in a macro nobody calls , protected by an ENV that nobody sets thus it never really executes.
