### ISSUE TITLE
LIVEONLY Tests in Attestation 

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4176]
there are 3 tests marked as LIVEONLY in attestation. due to the overcomplicated complexity of the tests i could not find the actual body of the test. thus i had to come up with a magic scheme to mark them as LIVEONLY.

**Comment by gearama** [comment]
removing myself from it

**Comment by RickWinter** [comment]
@LarryOsterman Although not ideal to have LIVEONLY tests its not always wrong. Is there any reason to make those tests run in recorded mode?

**Comment by LarryOsterman** [comment]
The LIVEONLY attestation tests cannot work against recordings because they depend on functionality that cannot work in a recording.

For instance, AddPolicyManagementCertificate requires an X.509 certificate which is created during new-testresources. That certificate is used to provision the test resources, and appears in the recordings. When run against a recording, the certificate in the recording will not match the certificate in the test, unless we create the attestation service instance inside the test directly.

**Comment by LarryOsterman** [comment]
Answering my own question. The tests were PolicyTests_ModifyGeneratedKey_AAD. That test is implemented in `ModifyPolicySecuredTest`. I'm not 100% sure why this test didn't work against the recordings though.
