### ISSUE TITLE
WinHTTP transport testing is not covered in CI pipeline. Is this by-design?

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#4245]
For example, in this run of pipeline https://dev.azure.com/azure-sdk/public/_build/results?buildId=2111147&view=logs&jobId=1dc92ddd-0ceb-5158-bd95-50f5fb549a36

under `Validate Win2019_x64_Release_WinHttp`, the tests were not run. same for `Win2022_UWP_release_x64` and `Validate Win2022_UWP_debug_x64`

```
Starting: Test
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_work\_temp\dbf37622-b37f-48db-a401-8ab738f66705.ps1'"
Cannot find file: D:/a/_work/1/s/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/a/_work/1/s/build/DartConfiguration.tcl
   Site: 
   Build name: (empty)
Create new tag: 20230112-0532 - Experimental
Cannot find file: D:/a/_work/1/s/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/a/_work/1/s/build/DartConfiguration.tcl
Test project D:/a/_work/1/s/build
Constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
Finishing: Test
```

under `Validate Win2022_Win32Api_debug_tests_x86`, both libcurl and WinHTTP were built, but libcurl was used for testing.
and it's the same for `Validate Win2022_Win32Api_debug_tests_x64`

**Comment by antkmsft** [comment]
@gearama, could it be that the previous record and playback only supported libcurl, but now we can actually update the CI matrix to enable WinHTTP?

**Comment by LarryOsterman** [comment]
We intentionally do not run tests on UWP builds.

Looking at the linked pipeline run, we run tests on WinHTTP and CURL. There are some test cases in WinHTTP which explicitly use CURL so there are traces generated which indicate that CURL is being used, but the vast majority of tests are actually using WinHTTP for the tests.

FOr instance:
```
2023-01-12T05:37:51.4791280Z 248: [2023-01-12T05:37:51.4788927Z] INFO  : Status operation: 1(WINHTTP_CALLBACK_STATUS_RESOLVING_NAME )
2023-01-12T05:37:51.5000346Z 248: [2023-01-12T05:37:51.4997571Z] INFO  : Status operation: 2097152(WINHTTP_CALLBACK_STATUS_REQUEST_ERROR )
2023-01-12T05:37:51.5003778Z 248: [2023-01-12T05:37:51.5001260Z] ERROR : Request error.  Error Code: 12007: The server name or address could not be resolved
2023-01-12T05:37:51.5004992Z 248: . 5
2023-01-12T05:37:51.5007535Z 248: [2023-01-12T05:37:51.5005381Z] DEBUG : WinHttpRequest::~WinHttpRequest. Closing handle synchronously.
2023-01-12T05:37:51.5010208Z 248: [2023-01-12T05:37:51.5007315Z] INFO  : Status operation: 2048(WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING )
2023-01-12T05:37:51.5013483Z 248: [2023-01-12T05:37:51.5008789Z] DEBUG : Closing handle; completing outstanding Close request
2023-01-12T05:37:51.5014641Z 248: [2023-01-12T05:37:51.5010355Z] WARN  : HTTP Transport error: Error while waiting for a send to complete. Error Code: 12007: The server name or address could not be resolved

```

**Comment by Jinming-Hu** [comment]
@LarryOsterman , can you paste the link of job you were looking at? I'm looking at Job `Validate Win2022_Win32Api_debug_tests_x64`. In the raw log, there are 23518 matches if I search `CURL Transport Adapter`, and 359 matches if I search for `WinHTTP`. So most of the requests are using libcurl rather than WinHTTP.

I found this issue when I was working on the new test proxy for storage. An issue I fixed is that the recordings made with libcurl cannot used by WinHTTP. If WinHTTP was used for storage CI, CI should've failed.

Can we leave this issue open for a few more days?

**Comment by LarryOsterman** [comment]
I was using the [test job you linked above]( https://dev.azure.com/azure-sdk/public/_build/results?buildId=2111147&view=logs&jobId=1dc92ddd-0ceb-5158-bd95-50f5fb549a36).

Looking at the test matrix definitions, the Win32Api_debug_tests tests are built with both CURL and WinHTTP. This configuration actually matches the configuration that our customers use, so it's a reasonable choice for the CI pipeline (the _curl tests force the use of CURL on WIndows by disabling building the WinHTTP pipeline).

The root cause of the behavior you're observing (lot's of CURL traces in the pipeline logs) is a behavior in the test_base class.

If your tests are using the test_base class, the `TestProxyManager::ConfigureInsecureConnection` test will alway use CURL when communicating with the test proxy because of the way the conditionals are set - if both CURL and WinHTTP are configured, the `ConfigureInsecureConnection` call always chooses CURL.

As things currently stand, the core premise of the bug ("WInHTTP is not tested in the CI pipeline") does not appear to be accurate - all of the evidence I have seen indicates that the tests are being run in the CI pipeline.

There is a separate issue of the `ConfigureInsecureConnection` forcing CURL (and overriding the normal defaults for transport adapter). IMHO this is a mistake - the Test Proxy Manager should follow the same platform-specific defaults.

We can leave it open for a few more days if you would like, but I'm not sure what benefit that would have.

**Comment by Jinming-Hu** [comment]
I looked through the impl of `ConfigureInsecureConnection` and now I got it. Thanks for the detailed explanation. @LarryOsterman 

I keep this issue open just to make sure I understand why this issue happens. Now I'll close this issue.
