### ISSUE TITLE
Minimize the use of `rand()` within the SDK within keyvault

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4291]
Follow-up from @LarryOsterman: https://github.com/Azure/azure-sdk-for-cpp/pull/4222#discussion_r1067352922
> FWIW, `rand` is considered a banned API when "randomness is required". Unless you call `srand()` and provide a high quality (unpredictable) seed, the output of `rand` is predictable which might result in collisions.
> 
> You might consider changing this to `rand_s`?

https://github.com/Azure/azure-sdk-for-cpp/blob/a3e9ad1d2c2509608ba6aaf78d0a400587e9b4fe/sdk/keyvault/azure-security-keyvault-secrets/test/perf/inc/azure/keyvault/secrets/test/get_secret_test.hpp#L78

Currently, it is only used within tests which makes it less critical to fix, but if collisions occur, it might affect test reliability.

**Comment by ahsonkhan** [comment]
@LarryOsterman, as an aside, we have one **actual** use of `rand()` in the SDK within the retry_policy, however that scenario doesn't require "true" randomness with guarantees around collision.
https://github.com/Azure/azure-sdk-for-cpp/blob/a3e9ad1d2c2509608ba6aaf78d0a400587e9b4fe/sdk/core/azure-core/src/http/retry_policy.cpp#L77

What are your thoughts on keeping that one?

**Comment by LarryOsterman** [comment]
For the retry policy, it's probably just fine.

For context: there are two concerns w.r.t. quality randomness - the primary one is when you use random as a source for things where predictability is critical. Two examples:
1. There was a famous hack of an online poker site caused by a predictable seed being used for a rnj (not finding the reference right now)
2. You can hijack TCP connections if you can predict the TCP frame sequence numbers - this was a BIG issue around the 2000s because many TCP implementations used highly predictable sequence numbers.

The secondary one is related, but it has to do with repeatability of random number sequences: If you call the `rand()` without first calling `srand()` with a unique input, then the output of the RNG is 100% repeatable. That means that if (for instance), you're generating temporary filenames, if you just use rand() as a source of uniqueness, then your filenames are going to collide, which is a VERY bad quality in a temporary filename.

For the retry policy, I don't believe that either of these concerns applies - clearly predictability isn't a problem, and if the same retry delays happen every time, it doesn't really matter.

**Comment by RickWinter** [comment]
rand() will eventually collide even when using srand().  This was the problem I faced in the uuid and why I switched to random_device.  We do want some randomness in the retry so that backoffs don't delay the same amount and continue to collide.  
I'm not convinced this a problem worth fixing though.  If we do address it, we need to ensure the `std::random_device` initialization cost is not occurring on each call.

**Comment by gearama** [comment]
with regards to KeyVault rand() appears only in 3 locations all tests not in the sdk code, i don't think randomness is that important in the test cases, where we generate an ephemeral string. 
As for the other locations it is used to get the backoff time for retry , and load balancing index , 
In all cases randomness / collisions don't seem to be of any import .
