### ISSUE TITLE
How to prevent request headers and query parameters from being redacted in log?

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#4359]
I was looking into some CI failures. But most of the response headers were redacted. So I couldn't find the useful information for troubleshooting.

I'd like to know if there's a proper way to tell the logging policy not to scrub these headers.

![image](https://user-images.githubusercontent.com/52266153/218908820-e53ab8ba-f65b-406e-90cb-1ce202879f28.png)

**Comment by Jinming-Hu** [comment]
CC @LarryOsterman @antkmsft @ahsonkhan

**Comment by LarryOsterman** [comment]
In general, you cannot - by default, all headers are assumed to contain PII unless otherwise allowed.

You can add headers to the list of allowed headers by modifying the LogOptions in the CLientOptions to allow additional headers and query parameters.

But there is no way of blanket allowing all headers into the traces.

**Comment by Jinming-Hu** [comment]
> In general, you cannot - by default, all headers are assumed to contain PII unless otherwise allowed.

I think most of the headers are fine to be displayed, like blob type, creation time, API version etc. Can I print these headers in unit testing by modifying log options, while keep the default behavior unchanged? I assume this doesn't violates any policy or guidelines.

**Comment by LarryOsterman** [comment]
I believe that the default allow list includes all the standard headers which are safe to be displayed. If your service has custom headers which are safe to be displayed, it can add those headers to the LogOptions list. 

And of course, your tests can do whatever they want to do, since they're effectively customer code (and customers can always add whatever headers they want to add).

If there are other standard headers which are safe to be displayed, please let us know and we'll add them.

**Comment by Jinming-Hu** [comment]
Will follow up in https://github.com/Azure/azure-sdk-for-cpp/issues/4359
