### ISSUE TITLE
Create a workload identity credential for DAC auth flow

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-cpp#4471]
**Intro:**
Azure AD workload identity federation is a new capability. It applies to both application identities and managed identities in Azure AD. The k8s team has built additional components around this that help customers **use this capability in their k8s deployments**. It's essential for the Azure Identity SDK to support this pattern so customers can easily benefit from this capability.

1. Allow customers to seamlessly move their code, which uses `DefaultAzureCredential`, to also run in a k8s cluster.
1. Do this in a way that isn't confusing to customers. They could either use application identities or managed identities. Telling a customer to pass a managed identity when they're using an application identity is going to be very confusing.
1. Provide predictability on the credential. For example, a customer may want to exclude `ManagedIdentityCredential`, so they know the request isn't going through the compute endpoint like IMDS.

**Proposal:**
1) Add a new credential type named `WorkloadIdentityCredential`. This new credential type will become part of the `DefaultAzureCredential` auth flow.

2) The `WorkloadIdentityCredential` will come into play if the necessary environment variables are populated: (`AZURE_FEDERATED_TOKEN_FILE`, `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`). These are set up by the k8s platform based on the assertions on a service account.

3) Allow an optional client ID parameter to be passed into `DefaultAzureCredential`, which can be used by the customers to override the `AZURE_CLIENT_ID` in the event they have more than one identity for which they intend to use this flow.

With these changes, customers can do the following:

1. Use `DefaultAzureCredential` as their main guidance to their developers.
1. Recommend excluding the necessary credential types to get predictability in their code execution.
1. Pass explicit client IDs for which they want to get an Azure AD token.

Ideally with these changes, we'd also remove the current implementation where `ManagedIdentityCredential` is overloaded to work with these env. Doing this is ideal to avoid the ensuing confusion for customers.

**Comment by Tom-Newton** [comment]
Thanks for adding the workload identity support in https://github.com/Azure/azure-sdk-for-cpp/pull/4872. 

However it looks like this issue is additionally asking for it to be added to the `DefaultAzureCredential`. Personally I would also find this valueable. It looks like [workload identity is included in the Python implementation of `DefaultAzureCredential`](https://github.com/Azure/azure-sdk-for-python/blob/1727c7aa8268fa4bdc88aef462e7106845900b79/sdk/identity/azure-identity/azure/identity/_credentials/default.py#L37-L38) so I think it makes sense to be consistent.

**Comment by ahsonkhan** [comment]
It was an intentional design decision to keep WIC out of the DAC, for now, especially since we don't have all the options added to DAC that some of the other languages have (and don't currently plan to).

Can you share more details on your scenario where you are using the DAC and why adding WIC to that would be helpful? Thank you for the feedback!

**Comment by Tom-Newton** [comment]
Thanks for the info. I like the DAC because it allows writing code that can automatically authenticate to Azure in any properly configured environment. 

For example I have a function that fetches some data from blob storage and decodes it. This function needs to work in several different environments including: 1. locally on a developer's workstation where CLI auth is used, 2. on Azure VMs were managed identity is used, 3. in kubernetes where we would ideally use workload identity but currently use service principal. 

If my code directly interfaced with the Azure C++ SDK I could handle it relatively easily but when there is a 3rd party library in between its more difficult, especially if that library is actually python but using bindings to this C++ code.

**Comment by LarryOsterman** [comment]
Could you use ChainedTokenCredential to configure exactly the set of credentials that you think is appropriate for the environments in which your code is supported?

One of the challenges of DAC is that the customer doesn't have any control over the authentication schemes used, and sometimes DAC picks the "wrong" credentials.
