### ISSUE TITLE
using openssl

### ISSUE THREAD

**Issue by nrgiii** [Azure/azure-sdk-for-cpp#4523]
**Query/Question**
How do I tell vcpkg to use my openssl libraries? I've already set OPENSSL_ROOT_DIR=/mydir on the cmake cmd line to point at my openssl v3.0.8 build (built from source) and yet vcpkg still insists on downloading and building openssl from source itself. Building openssl succeeds on unbuntu 20 but fails on Centos 7.9, which I may file a bug report on if there is no way to make azure use the openssl libs I've already built. Complete build log is attached.

***Why is this not a Bug or a feature Request?***
It may be a bug or feature request. I don't have enough information to know that yet.

**Setup (please complete the following information if applicable):**
 OS: Linux (Ubuntu 20 and Centos 7.9, see above)
azure-sdk-for-cpp version: azure-identity_1.4.0 (tag)

 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Query Added
- [X] Setup information Added
[slowazure.log](https://github.com/Azure/azure-sdk-for-cpp/files/11172919/slowazure.log)

**Comment by ras0219-msft** [comment]
This will probably look very similar to using system package manager dependencies: https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/.

Instead of using entirely empty overlays, you might choose to copy your prebuilt files and headers into ${CURRENT_PACKAGES_DIR} to give vcpkg more visibility (more accurate binary caching, etc).

We would also love a PR into Microsoft/vcpkg to fix our build on CentOS!

**Comment by nrgiii** [comment]
The centos build works if I set the env vars CC and CXX to use the correct compiler. These were set on the cmake cmd line (-DCMAKE_CXX_COMPILER and -DCMAKE_C_COMPILER) but apparently that is not being passed to the openssl build done by vcpkg.

**Comment by RickWinter** [comment]
Thank you for reporting this issue.  It appears you have successfully been able to build.   We are looking into ways to make this easier.
