### ISSUE TITLE
ClientCertificateCredential - option to provide key without accessing file system

### ISSUE THREAD

**Issue by nrgiii** [Azure/azure-sdk-for-cpp#4583]
**Is your feature request related to a problem? Please describe.**
The only way to specify a private key to ClientCertificateCredential  s to provide a file path to the PEM file.
There needs to be a way to specify a private key without accessing the file system. The PEM string could
be provided directly to the class.

**Describe the solution you'd like**
An option or another class where the PEM string can be provided directly removing the need to access the file system.
Even better would be a class that accepts an OpenSSL BIO, which can be used to read the key from memory, file system, etc.

**Describe alternatives you've considered**
This would be a very clunky hack:
-create a temporary PEM file with the key.
-create ClientCertificateCredential 
-delete the temporary file.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by ahsonkhan** [comment]
Hello @nrgiii, 
We’ve added the feature requested by you, as a beta release, last week (1.10.0-beta.1). Please give it a try and let me know how it goes, or if you uncover any blockers 😊
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/identity/azure-identity/CHANGELOG.md#1100-beta1-2024-09-17

If you use vcpkg, it is available via our vcpkg beta registry:
https://github.com/Azure/azure-sdk-vcpkg-betas/tree/main

I would like to gather some feedback on our design choices/documentation here and understand your needs a bit better:
Regarding reading the key and cert from memory, we added the ability to provide both a private key and a signing certificate directly, rather than us reading it from a file. We support the RSA format of the private key and we expect both the key and cert to be in PEM encoded format. Therefore, we accept those input parameters as `std::string`. Is that the format in which you’d have the key and cert so that you can call the API with the expected values? If you have the data in a different format (say BER/DER binary), it would require transforming to PEM. Do you have private keys in a format other than RSA? We have documented the new ctor as follows. Please let me know if that works for your scenario:
https://github.com/Azure/azure-sdk-for-cpp/blob/610c85d7684f9a384c3e72bb9a41068d41f521d1/sdk/identity/azure-identity/inc/azure/identity/client_certificate_credential.hpp#L126-L142

Thanks!
