### ISSUE TITLE
Feature request: `HttpAuthorization` class in core sdk

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#4718]
**Is your feature request related to a problem? Please describe.**
Storage team is going to implement a feature in STG78. With this feature, customer can copy a blob or block from source to destination with two different authentication methods for source, destination respectively.

We'll need a field in function options bag so that customer can provided an OAuth token. Type for this field in other language SDK is `HttpAuthorization`. But we do not have this type in C++ yet.

[Link for .Net](https://github.com/Azure/azure-sdk-for-net/blob/9f97137c0d2822905902605ba896894cd5badc8f/sdk/core/Azure.Core/src/HttpAuthorization.cs#L12)
[Link for Java](https://github.com/Azure/azure-sdk-for-java/blob/769e05a0d44fa999446b09c26f151f95815e358b/sdk/core/azure-core/src/main/java/com/azure/core/http/HttpAuthorization.java#L15)

**Describe the solution you'd like**
Core SDK can provide such a type, like in .Net and Java.

**Describe alternatives you've considered**
None

**Additional context**
The option bag in .Net: https://github.com/Azure/azure-sdk-for-net/blob/9f97137c0d2822905902605ba896894cd5badc8f/sdk/storage/Azure.Storage.Blobs/src/Models/AppendBlobAppendBlockFromUriOptions.cs#L49

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Jinming-Hu** [comment]
@RickWinter Can you take a look at this feature request?

**Comment by ahsonkhan** [comment]
After some deliberation on the feature request and how other languages ended up where they did with this request, here is the proposal we recommend in C++:

Add a public `std::string` field within the options classes that need this feature, rather than a strongly typed `HttpAuthorization`.
https://github.com/Azure/azure-sdk-for-cpp/blob/86612b57fa78e2961aa731c06a221553c8f9d564/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_options.hpp#L1267-L1285
```C++
struct AppendBlockFromUriOptions final
{
    // Comment from rest api spec along with example accepted string, showcasing the format
    std::string SourceAuthorization;
}
```

**Design Notes:**
- I recommend that the name of the string option match the rest API docs/header (`x-ms-copy-source-authorization`), and call it `SourceAuthorization` and not `SourceAuthentication`. Authorization and Authentication are similar but subtly different concepts.
- Add documentation, in the comment, to show an example of what the string format should look like for that option (something like "Bearer <Foo>"), so the user knows what to pass. https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url?tabs=azure-ad#request-headers
- You can use the empty string sentinel to mean the option is not set, and hence don't set the header. This is fairly stable, and hence we don't need to use `Nullable` here.
```C++
if (!sourceAuthorization.empty())
   // set copy source header in the request
```

This is similar to how GoLang ended up implementing support for this feature.
https://github.com/Azure/azure-sdk-for-go/blob/ceca0856d1f2657f4a81dadb727480a92050299f/sdk/storage/azblob/blockblob/models.go#L78-L79

I considered exposing the option as a `TokenCredential`, with the scheme being hardcoded within the storage SDK as `Bearer`, but it looks like an important scenario here is to enable non-Msft authorization mechanisms that are not `Bearer`.

**This conclusion based on a couple of realization:**
1) There hasn't been any need for a general purpose `HttpAuthorization` feature that would need to be present in Azure::Core for many services, beyond the specific needs of the storage service (even in the other languages that have it). Therefore, **IF** such a type needs to exist, we recommend keeping it in `Azure::Storage` until concrete evidence of it required by others.
2) The type, on its own, as a tuple of 2 strings (scheme and parameter), does not provide enough usability benefit to the end user, to justify introducing a type, even in storage. We should be exposing the options field as a string, and use documentation to let the caller know how to provide that string (`"<scheme><space><parameter>"`). If you, as the storage area owner, feel strongly that such a simple type makes a meaningful usability difference to our customers, then that is your decision. In that case, I recommend a name such as `CopyHttpAuthorization` to avoid burning the general purpose name, for future use.

**Comment by Jinming-Hu** [comment]
@ahsonkhan This proposal sounds good to me.

This way, C++ SDK won't be aligned with .Net, Java etc. @LarryOsterman Do you have any concern here?

**Comment by LarryOsterman** [comment]
> @ahsonkhan This proposal sounds good to me.
> 
> This way, C++ SDK won't be aligned with .Net, Java etc. @LarryOsterman Do you have any concern here?

Ahson and I chatted about this last week. As far as I know, no other services need this functionality and as such, it probably shouldn't be in Core (roughly speaking, the rule is "if more than one service is going to use this functionality, it belongs in core, otherwise it belongs in the service").

If there are other services beyond Storage that need this functionality, we can reconsider.

**Comment by ahsonkhan** [comment]
> This way, C++ SDK won't be aligned with .Net, Java etc.

That is OK in this case. Idiomatic to language is higher priority compared to consistency across languages. And sometimes the decisions other languages take is ecosystem specific and if it makes sense to do something differently (after learning from their experience), that is acceptable.

One other example where we use `std::string` in C++ as the exchange type instead of something strongly typed is `Url`, even though we have the type available in core.
