### ISSUE TITLE
Exception thrown without meaningful StatusCode and ReasonPhrase when incorrect SSL CA cert's path is given

### ISSUE THREAD

**Issue by phoebusm** [Azure/azure-sdk-for-cpp#4738]
**Describe the bug**
Exception thrown without errorcode when SSL CA cert's path is given

***Exception or Stack Trace***
`Azure::Core::RequestFailedException` is thrown. However its `StatusCode` is 0 and `ReasonPhrase` is empty.

**To Reproduce**
Connect to Azure file storage with https connection and invalid cert path.

***Code Snippet***
```
Azure::Core::Http::CurlTransportOptions curl_transport_options;
curl_transport_options.CAInfo = "/abc";
BlobClientOptions client_options;
client_options.Transport.Transport = std::make_shared<Azure::Core::Http::CurlTransport>(curl_transport_options);
auto container_client = BlobContainerClient(endpoint, credentials, client_options);
auto page = container_client.ListBlobs(options);
```
**Expected behavior**
Exception should be thrown with meaningful `StatusCode` and `ReasonPhrase`.

**Screenshots**
Not applicable

**Setup (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - IDE : Doesn't matter
 - Version of the Library used: azure-core_1.10.0

**Additional context**
User can only figure out the cause of the exception by turning the log on;
`export AZURE_LOG_LEVEL=1`
Then below warning message will appear to point out the problem:
`[2023-06-27T10:13:55.7190420Z] WARN  : HTTP Transport error: Fail to get a new connection for: https://arcticdbtest.blob.core.windows.net. Problem with the SSL CA cert (path? access rights?)`

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by ronniegeraghty** [comment]
Hi @phoebusm. Thank you for reaching out and we regret that you're experiencing difficulties. We are currently looking into this issue and will follow up in the comments of this issue. Please monitor this issue for updates.

**Comment by ahsonkhan** [comment]
The reason why the StatusCode and ReasonPhrase aren't set is because we are throwing a TransportException (which derives from RequestFailedException), at the CurlConnection ctor, **before** the request is actually sent to the service. There is no response from the service to fill that info from.

The object hierarchy, where TransportException derives from RequestFailedException might be causing some mismatch of expectations there.

Also, I believe, you can use the `.what()` string on the exception thrown to see the error message, so you don't solely have to rely on the logging. 

https://github.com/Azure/azure-sdk-for-cpp/blob/25f3b9a228a928f5f4e6de550f656f169f8440bf/sdk/core/azure-core/src/http/curl/curl.cpp#L2183-L2448
