### ISSUE TITLE
Make `WorkloadIdentityCredential` part of the `DefaultAzureCredential`

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4906]
We want to follow how other language SDKs behave, and put `WIC` within the `DAC`, in the same order (before `ManagedIdentityCredential`).

Example:
https://github.com/Azure/azure-sdk-for-go/blob/e7968b534c61da1e38a683e21ac690deb14833c7/sdk/azidentity/default_azure_credential.go#L41-L51

Update the doc as well once that's done, so there's no exception necessary to document:
https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#azure-identity-client-libraries

cc @chlowell, @scottaddie

**Comment by LarryOsterman** [comment]
> When would the patch be formally released? Our cloud service on azure is counting on this. 👀 Any ETA?

Is your cloud service using `DefaultAzureCredential` in production? In general we strongly recommend against using `DefaultAzureCredential` in any environment other than testing, because its behavior can be unpredictable.

We typically prefer using `ChainedTokenCredential` for customers who want to support multiple authentication schemes in production since it gives them full control over the authentication process. 

And that functionality is available today.

The `WorkloadIdentityCredential` functionality is currently available in our 1.6.0-beta.1 package which is in the Azure C++ SDK beta catalog. The beta catalog can be found at https://github.com/Azure/azure-sdk-vcpkg-betas. 

If your team has the bandwidth, it would be wonderful if you could try `WorkloadIdentityCredential` to confirm that it meets your needs.

**Comment by haorenfsa** [comment]
> Is your cloud service using DefaultAzureCredential in production?

No, our service is still in pre-prod stage. We'll check `ChainedTokenCredential` 

> The WorkloadIdentityCredential functionality is currently available in our 1.6.0-beta.1 package which is in the Azure C++ SDK beta catalog. The beta catalog can be found at https://github.com/Azure/azure-sdk-vcpkg-betas.

By the way, is `WorkloadIdentityCredential` included, (or will be included) in `ChainedTokenCredential`? Or should we use `WorkloadIdentityCredential` deliberately?

**Comment by LarryOsterman** [comment]
> > Is your cloud service using DefaultAzureCredential in production?
> 
> No, our service is still in pre-prod stage. We'll check `ChainedTokenCredential`
> 
> > The WorkloadIdentityCredential functionality is currently available in our 1.6.0-beta.1 package which is in the Azure C++ SDK beta catalog. The beta catalog can be found at https://github.com/Azure/azure-sdk-vcpkg-betas.
> 
> By the way, is `WorkloadIdentityCredential` included, (or will be included) in `ChainedTokenCredential`? Or should we use `WorkloadIdentityCredential` deliberately?

`ChainedTokenCredential` allows the customer to specify any `TokenCredential` based credential providers, including `WorkloadIdentityCredential`. If your scenario involves multiple possible credential providers, it gives you the flexibility of using multiple providers and defining the order for each one to be applied.

**Comment by haorenfsa** [comment]
Thank you so much!

**Comment by ahsonkhan** [comment]
Docs fix-up here: https://github.com/MicrosoftDocs/azure-docs-pr/pull/251238
