### ISSUE TITLE
Add logging on successful creation and on errors within the WorkloadIdentityCredential

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4947]
Similar to the other credential types, like `EnvironmentCredential`, add logging and update the DAC LogMessages unit test as appropriate.

https://github.com/Azure/azure-sdk-for-cpp/blob/79737f14738b60617404e69a2ac503066ad2afe7/sdk/identity/azure-identity/src/environment_credential.cpp#L100-L130

https://github.com/Azure/azure-sdk-for-cpp/blob/79737f14738b60617404e69a2ac503066ad2afe7/sdk/identity/azure-identity/test/ut/default_azure_credential_test.cpp#L42

**Comment by ahsonkhan** [comment]
Also add log messages to environment variables that are expected to be set and aren't, which we were previously throwing an exception from on construction (see https://github.com/Azure/azure-sdk-for-cpp/pull/4951).

**Comment by antkmsft** [comment]
I agree that we need to log, just a thought on logging the env variables.

Maybe, we don't need to go into detail of which exactly variables were not set, and can just mention that the pod/Kubernetes is not configured.

Unlike EnvironmentCredential, where it is the user who is supposed to set the variables, for WorkloadIdentity it is the Azure who configures them, correct?

It is the same case as with ManagedIdentityCredential: it also depends on environment variables, but in the log messages it does not explain which ones it reads from and which ones were not set - because it is not up to the user to set them, the error most probably would be unactionable for the user, could be even misleading as of steps to get it fixed. I.e. it is not like the user should go and set some variable on a managed identity machine, but just rather go to the Azure portal and flip the switch to enable managed identity. I think, with WorkloadIdentityCredential + Kubernetes, experience is pretty similar.

**Comment by antkmsft** [comment]
Also, a workload_identity_sample does mention, which variables need to be set.
Instead, I think, we should put a link to setting up WorkloadIdentity to work in Kubernetes in Azure.

**Comment by joshfree** [comment]
@ahsonkhan is this still happening for the November release milestone? If not can you update the issue/milestone accordingly?
