### ISSUE TITLE
[azure-identity-cpp] Build error on x64-windows with VS2017

### ISSUE THREAD

**Issue by SharkyChen** [Azure/azure-sdk-for-cpp#5554]
I found that when I compile with vs2017 there will be many errors.

like
```
\sdk\identity\azure-identity\src\azure_cli_credential.cpp(80): error C2653: 'Core': is not a class or namespace name
\sdk\identity\azure-identity\src\client_certificate_credential.cpp(465): error C2061: syntax error: identifier 'ClientCertificateCredentialOptions'
```
But it can work when I use vs2022, so I wonder if it doesn't support VS2017?
![1713513378381](https://github.com/Azure/azure-sdk-for-cpp/assets/130737040/dc9ac0e2-26c3-4e08-95e0-0d86cc864042)

**Comment by ahsonkhan** [comment]
VS 2017 is not part of our support matrix of compilers (and its [mainstream support date ended in April 2022](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2017)).

Given VS 2022 works for you already, is there any reason you need to keep using VS 2017? I recommend updating to VS 2202, since that is still in support, and it matches how we build/test the Azure SDK.
