### ISSUE TITLE
Getting issue in nullable.hpp file while integrating the azure sdk for cpp into our application

### ISSUE THREAD

**Issue by yashshah-22** [Azure/azure-sdk-for-cpp#5634]
**Query/Question**
Getting issue 
Error	C2556	'int64_t *Azure::Nullable<int64_t>::operator ->(void) const': overloaded function differs only by return type from 'const int64_t *Azure::Nullable<int64_t>::operator ->(void) const' (compiling source file login.cpp) in file nullable.hpp while integrating azure sdk into our project.I have not made any changes in the file still getting the errors.

In login.cpp I have used header files 
#include<azure/identity.hpp>
#include<azure/core.hpp>

***Why is this not a Bug or a feature Request?***

The problem could be resolved by adjusting the implementation to avoid overloading based only on return type. This typically involves refactoring the function signatures or ensuring that only one version of operator-> exists.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Visual Studio Community 2015

**Comment by LarryOsterman** [comment]
I'm a tad confused. Based on my reading of the source code, there are two *different* declarations of the `operator->` method. 

At [line 281](https://github.com/Azure/azure-sdk-for-cpp/blob/a315b29babba6a83656b7043ca4feea8edf45529/sdk/core/azure-core/inc/azure/core/nullable.hpp#L281), we have:

```c++
  constexpr const T* operator->() const { return std::addressof(m_value); }
```
which applies to `const Nullable` values.

At [line 291](https://github.com/Azure/azure-sdk-for-cpp/blob/a315b29babba6a83656b7043ca4feea8edf45529/sdk/core/azure-core/inc/azure/core/nullable.hpp#L291) we have:

```c++
  constexpr T* operator->() { return std::addressof(m_value); }
```

which applies to `Nullable` values (mutable or non-const). So there shouldn't be any ambiguities in the implementation.

Your bug report doesn't indicate which line is upsetting the compiler, so it's hard to fully understand what is causing challenges.

If it is possible to build a stand-alone reproduction of the problem, it would help a great deal in understanding the problem.

I did notice that you are using a rather old version of Visual Studio community edition (2015). We don't include this version of the compiler in our tests because it is a fairly old version of the compiler.

Would it be possible to try this on a newer version of Visual Studio? There have been many language compliance related changes made to Visual Studio over the past 8 years which may be affecting your code.

**Comment by yashshah-22** [comment]
Yes , I will try with Visual Studio 2022 and let you know . Thanks!!!!!

**Comment by LarryOsterman** [comment]
@yashshah-22, apparently our bot didn't notice you had replied - feel free to ignore that :).

Looking forward to your update.
