### ISSUE TITLE
Run policheck over the repo as part of the next release

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#564]
Similar to https://github.com/Azure/azure-sdk-for-c/issues/1175

**Comment by weshaggard** [comment]
We have a general issue at Azure/azure-sdk#616 tracking this but unfortunately there isn't any great way to automate this we can do a manual run and report generation but the tools aren't very good for automation.

**Comment by ahsonkhan** [comment]
Ran v5.9.5 against 864582b10e26897b26f0c6ce42b35c0b4edc1a51 and found an issue fixed by https://github.com/Azure/azure-sdk-for-cpp/pull/610, for the upcoming release.

Moving to next milestone.

**Comment by RickWinter** [comment]
@weshaggard, @kurtzeborn  Is automation of this tool for all repos something Central-EngSys can enable in MQ?

**Comment by weshaggard** [comment]
This isn't something on my radar during the MQ timeframe and I think automation will be difficult because of the restrictions we have on running the tools (namely the reporting tools require domain joined machines). 

@RickWinter is there something beyond trying to eliminate this manual release step that is driving the question? If so we can talk about potential options.

**Comment by RickWinter** [comment]
@weshaggard The drive behind this is to eliminate a manual release task required for every release.

**Comment by antkmsft** [comment]
@ahsonkhan, can you take care of this since you did this for the C repo?

**Comment by ahsonkhan** [comment]
Yes, I can.

**Comment by ahsonkhan** [comment]
Ran v510 against 6b9b57815e86abc13820b482a3116d8c44b1eb23 and found no issues, for the upcoming release.

**Comment by antkmsft** [comment]
Thank you @ahsonkhan!
