### ISSUE TITLE
Add exceptions guidelines

### ISSUE THREAD

**Issue by gilbertw** [Azure/azure-sdk-for-cpp#61]
Update SDK guidelines with usage patterns for exceptions

**Comment by BillyONeal** [comment]
How is this different than the https://azure.github.io/azure-sdk/cpp_design.html status quo ? (I'm reacting strongly to this because this section is probably the part we've litigated the most so far, so short of adding concrete code examples I don't think we should change the guidance unless something has substantially changed since then.)

**Comment by gilbertw** [comment]
This isn't about redoing those sections.  Its about expanding on what's there.  We think it makes sense to put tighter bounds on what is thrown.
i.e. We should mandate exceptions derive from the exception Class hierarchy.

Also we should add guidelines for usage of noexcept

**Comment by vhvb1989** [comment]
We have decided to use runtime exception, so I consider this issue as resolved.

@gilbertw , do you want to close it?

**Comment by RickWinter** [comment]
Exception section is added to the design guidelines
