### ISSUE TITLE
Transient core ctest failure

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#634]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=531116&view=logs&j=becb4c78-6d46-5b40-696d-491037a3748a&t=7da4ec77-80ef-5cae-b212-17e17d7c0a17&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c

```

1: [==========] 50 tests from 8 test suites ran. (186524 ms total)
1: [  PASSED  ] 48 tests.
1: [  FAILED  ] 2 tests, listed below:
1: [  FAILED  ] TransportAdapter.getMultiThread
1: [  FAILED  ] TransportAdapter.ConnectionPoolCleaner
1: 
1:  2 FAILED TESTS
1/1 Test #1: azure-core-test ..................***Failed  186.80 sec

```

This test failed once and then succeeded on a second run.

**Comment by vhvb1989** [comment]
might be related to https://github.com/Azure/azure-sdk-for-cpp/pull/640
If for any reason a new connection failed to be open with secure channel, instead of trying again, we were throwing, making test to fail.
Will leave it open for now until that PR is merged and then I will check for some time if we see this issue again
