### ISSUE TITLE
Transient core ctest failure

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#635]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=531279&view=logs&j=becb4c78-6d46-5b40-696d-491037a3748a&t=7da4ec77-80ef-5cae-b212-17e17d7c0a17

```
1: [----------] Global test environment tear-down
1: [==========] 50 tests from 8 test suites ran. (186694 ms total)
1: [  PASSED  ] 49 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] TransportAdapter.customSizePut
1: 
1:  1 FAILED TEST
1/1 Test #1: azure-core-test ..................***Failed  186.90 sec

```

**Comment by vhvb1989** [comment]
might be related to https://github.com/Azure/azure-sdk-for-cpp/pull/640
If for any reason a new connection failed to be open with secure channel, instead of trying again, we were throwing, making test to fail.
Will leave it open for now until that PR is merged and then I will check for some time if we see this issue again
