### ISSUE TITLE
connection cannot be reused after performing PATCH operation.

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#658]
i'm going to add some more information later.

**Comment by Jinming-Hu** [comment]
```
#include <iostream>

#include "azure/storage/files/datalake/datalake.hpp"
#include "samples_common.hpp"

int main()
{
  using namespace Azure::Storage::Files::DataLake;

  std::string fileSystemName = "sample-file-system";
  std::string fileName = "sample-file";

  auto fileSystemClient
      = FileSystemClient::CreateFromConnectionString(GetConnectionString(), fileSystemName);

  try
  {
   fileSystemClient.Create();
  }
  catch (Azure::Storage::StorageError& e)
  {
    unused(e);
  }

  auto fileClient = fileSystemClient.GetFileClient(fileName);
  fileClient.Create();

  auto acls = fileClient.GetAccessControls()->Acls;

  for (int i = 0; i < 3; ++i)
  {
    fileClient.SetAccessControl(acls); // This connection cannot be reused, although it returns 200
  }
}
```

**Comment by Jinming-Hu** [comment]
![image](https://user-images.githubusercontent.com/52266153/93298141-45fe6600-f825-11ea-9399-5e9532143d02.png)

**Comment by vhvb1989** [comment]
@Jinming-Hu there are 2 things happening in the provided code. I don't think neither of them is a bug.

1) First case, "Container does not exists on account". This is the very first time we run this code. The first call to `fileSystemClient.Create()` creates a new curl connection and creates the file system in the account (the container). Notice that the host that is used for this request is like `storageaccount.blob.core.windows.net`.  
Then, the next network call is to create the file. The host in this request changes to something like `storageaccount.dfs.core.windows.net`. Since the host is different than the previous call, a new curl connection is created.
After this, all the following calls are done to the same host, and the connection is reused.  At the end, 2 connections are used in total.

2) Second case is when the fileSystem already exists.  In this case, the first call returns with a 409 (like the img you shared). As per design, we can't reused connections after server returns an error code (usually server closes the connection right after).  So the connection is not moved back to the pool.  This means that any new call will create a new connection.
The call to `create` for the file works even if there is already one in the account. It returns 201 and the connection is reused after it for all following calls.

I am going to close this issue based on this explanation.  
Please feel free to re-open it if there is something I didn't understand on my side or if you still believe there is something we need to fix in there.

**Comment by Jinming-Hu** [comment]
> @Jinming-Hu there are 2 things happening in the provided code. I don't think neither of them is a bug.
> 
> 1. First case, "Container does not exists on account". This is the very first time we run this code. The first call to `fileSystemClient.Create()` creates a new curl connection and creates the file system in the account (the container). Notice that the host that is used for this request is like `storageaccount.blob.core.windows.net`.
>    Then, the next network call is to create the file. The host in this request changes to something like `storageaccount.dfs.core.windows.net`. Since the host is different than the previous call, a new curl connection is created.
>    After this, all the following calls are done to the same host, and the connection is reused.  At the end, 2 connections are used in total.
> 2. Second case is when the fileSystem already exists.  In this case, the first call returns with a 409 (like the img you shared). As per design, we can't reused connections after server returns an error code (usually server closes the connection right after).  So the connection is not moved back to the pool.  This means that any new call will create a new connection.
>    The call to `create` for the file works even if there is already one in the account. It returns 201 and the connection is reused after it for all following calls.
> 
> I am going to close this issue based on this explanation.
> Please feel free to re-open it if there is something I didn't understand on my side or if you still believe there is something we need to fix in there.

This isn't what i was talking about. I was talking about the last three requests, all of which were sent to `storageaccount.dfs.core.windows.net` and returned `200`.

**Comment by Jinming-Hu** [comment]
@vhvb1989 This issue doesn't exist on Linux

**Comment by Jinming-Hu** [comment]
Since we cannot reproduce this issue without a proxy, I removed the `blocking-release` tag. We can investigate after Oct. release.

**Comment by RickWinter** [comment]
@Jinming-Hu Update the issue with repro instructions.
