### ISSUE TITLE
[Storage] Switch to use `Azure::Core::Http::Url::Encode` on all places where `Azure::Storage::Details::UrlEncodeQueryParameter` is used

### ISSUE THREAD

**Issue by katmsft** [Azure/azure-sdk-for-cpp#736]
https://github.com/Azure/azure-sdk-for-cpp/pull/598#discussion_r502324647

**Comment by katmsft** [comment]
And remove `Azure::Storage::Details::UrlEncodeQueryParameter`.

**Comment by Jinming-Hu** [comment]
Hi @ahsonkhan , what's your suggested way of encoding query parameter? Can you give me an example?

**Comment by Jinming-Hu** [comment]
@ahsonkhan ping...

**Comment by ahsonkhan** [comment]
Update all calls to `UrlEncodeQueryParameter` as follows:
https://github.com/Azure/azure-sdk-for-cpp/blob/843432172e11f8d84ce1571a862b85b0babde7c0/sdk/storage/azure-storage-common/src/crypt.cpp#L31
```C++
string doNotEncodQueryParameter = "!$&'()*,;/:@?";
Url::Encode(value, doNotEncodQueryParameter);
```

Update all calls to `UrlEncodePath` as follows:
https://github.com/Azure/azure-sdk-for-cpp/blob/843432172e11f8d84ce1571a862b85b0babde7c0/sdk/storage/azure-storage-common/src/crypt.cpp#L70
```C++
string doNotEncodPath = "!$&'()*,;/:@=";
Url::Encode(value, doNotEncodPath);
```

**Comment by Jinming-Hu** [comment]
@ahsonkhan 
we only need to pass one parameter to `UrlEncodePath`, but we have to pass two parameters to `Url::Encode`. The former looks more concise.

**Comment by ahsonkhan** [comment]
> we only need to pass one parameter to `UrlEncodePath`, but we have to pass two parameters to `Url::Encode`. The former looks more concise.

I understand. If you feel the usability burden is too high, then feel free to create a convenience wrapper around the `Encode` method, but try to place it in a header that is meaningful or feel like it belongs. If we expect a few of these helpers/utility methods, maybe we need an internal only `storage_utilities.hpp` file. I am not familiar with the ins-and-outs of the file/directory structure for storage, so open to hearing your suggestions for a good place.

> What if we define a function

I was going to suggest that exactly. The objective is to avoid duplication of core logic so that updates/fixes and testing can be made in one place and all callers benefit.

And then also make sure to keep/add comments in the code explaining why `UrlEncodePath` and `UrlEncodeQueryParameter` have different extra symbols that don't need encoding.
