### ISSUE TITLE
Remove unnecessary vcpkg environment variable requirement in cmakelist that is only needed for CI

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#754]
This section of cmakelist is not needed for the customer to build the SDK and we should do something else to fulfill the needs of the CI:
https://github.com/Azure/azure-sdk-for-cpp/blob/cd2a8a3812725c3524e5d5fd1ab49b9cb08e0890/CMakeLists.txt#L25-L35

Also update the docs (if any) to not need the triplet.

cc @vhvb1989

**Comment by ahsonkhan** [comment]
@antkmsft can you please elaborate?

**Comment by antkmsft** [comment]
AK> Hey Charlie, Victor told me that you don't recommend this kind of vcpkg integration; if so - why? It looks harmless to me, we only set CMAKE_TOOLCHAIN_FILE if it is not defined, and vcpkg is present - https://github.com/Azure/azure-sdk-for-cpp/blob/master/cmake-modules/AzureVcpkg.cmake#L9-L18

CB> part of it is personal preference, I prefer not to have my project's build system know/care about vcpkg.
CB> it's not _that_ bad
CB> I also don't love my build system trying to divine things about the building system based on environment variables and such
CB> that said, we do a similar thing in the STL and it works allright

AK> I understand, thank you! I'd say it has predictable and defined behavior, and it makes it easier for the new users to build, without the need to provide CMAKE_TOOLCHAIN_FILE in common configuration, so, it sounds like it has the right to exist?..

CB> I'd also just write that code before your toplevel "project" call instead of the macro
CB> it's not like you're going to be calling that macro multiple times
CB> yeah, it's not super bad

AK> thank you! The reason that it is in macro is that there are multiple entry points - you can either load the entire Azure SDK "solution", or the individual "project" ("projects" are primarily used when being built as vcpackages).

CB> yeah, I'd just put it on the toplevel one, I'm not sure how setting CMAKE_TOOLCHAIN_FILE works when you're set it between two calls to project()

AK> all works fine, and it is not going to be set multiple times, because once we set it, the next time the check of ifndef(CMAKE_TOOLCHAIN_FILE) is not going to let us through to set it again. This is what I like about this technique - it is "smart", but not too invasive.
AK> thank you Charlie!

**Comment by antkmsft** [comment]
That being said, there is an extra snippet we can remove, I'll do a PR for that.
